### ISSUE TITLE
api call to reload zones / pools configuration

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#100]
Would be good to have a way to reload the zones / pools configuration without restarting the server.

**Comment by andris9** [comment]
This is something I've wanted to do for a while and partially already works. When you send SIGHUP to the master process then configuration is reloaded from disk but this does not affect everything, eg worker counts do not change etc.

**Comment by dazoot** [comment]
Zones do not change that much, for this bug to be of a good use. Closing for now.
