### ISSUE TITLE
Static smtp auth possible?

### ISSUE THREAD

**Issue by apmcodes** [zone-eu/zone-mta#102]
Is it possible to configure a static smtp credential for each feeder interfaces by proving a user and pass in the Interfaces/feeder config instead of using external auth?

Tried the below in config/interfaces/feeder.toml, but any user/ pass is getting successful authenticated

  smtpInterfaces: 
   { feeder: 
      { ...
        authentication: true,
        user: 'XXXX',
        pass: 'XXXX',

Please clarify.

**Comment by martandya** [comment]
Same issue here too !!

**Comment by andris9** [comment]
See this [example plugin for using static auth](https://gist.github.com/andris9/938a73247b1e76ec515293f580dfa802)
