### ISSUE TITLE
clarify: bounces.txt slowdown action

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#103]
Is action slowdown from bounces.txt implemented ? What does it do ?

**Comment by andris9** [comment]
Could you explain your issue a bit more? Is bounces.txt making your server slow? It is a list of regexes for determining bounce status for rejected messages

**Comment by dazoot** [comment]
bounces.txt header states:
```
# Bounce rules list
# Format:
#   regex,action,reason,message
# action: defer, reject, slowdown
# reasons:
#   rate, block, spam, message, config, recipient, other, capacity, greylist, network, protocol, auth, blacklist
```
What does action stand for ?
What does action slowdown do ?

For example:
```
# Hotmail error messages
# https://mail.live.com/mail/troubleshooting.aspx
^421[ \-]+RP\-00\d,slowdown,rate,Rate limit exceeded
```

What does ZoneMTA do when a slowdown action is found in bounces.txt ?

**Comment by dazoot** [comment]
Thanks.
