### ISSUE TITLE
Stuck at installing 

### ISSUE THREAD

**Issue by martandya** [zone-eu/zone-mta#104]
Just start try to install ZoneMTA but stuck at start when i run command $ npm start 
i waited since last 2 hrs but nothing happened , its sucked at -

verb Plugins Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 3ms]
verb Plugins Initialized DKIM signer from <node_modules/zone-mta/plugins/core/dkim> [load time 1ms]
verb Plugins Initialized Loop Breaker from <node_modules/zonemta-loop-breaker> [load time 1ms]
info Sender/bounces/2120 3 plugins loaded
info Sender/bounces/2120[1] Created sender instance
info Sender/default/2119[1] Created sender instance
info Sender/default/2119[2] Created sender instance
info Sender/default/2119[3] Created sender instance
info Sender/default/2119[4] Created sender instance
info Sender/bounces/2120[2] Created sender instance
info Sender/default/2119[5] Created sender instance

seems script stopped or something els !!

**Comment by andris9** [comment]
This seems like an expected output, you should see it when you start the app. What do you mean that it got stuck?

**Comment by martandya** [comment]
means its stop at "" info Sender/default/2119[5] Created sender instance "" ...
i am waiting since last 1 hrs but still nothing ...

**Comment by andris9** [comment]
This is what you are supposed to see. The app created instance for sending mail and is now waiting for mail to send

**Comment by Manishjodhani** [comment]
Hi andris9,
I'm also facing same issue.
can you tell me where should i get the config file of it. so i can point my ip

**Comment by Manishjodhani** [comment]
Hi andris9,
Failure sending mail.
Unable to connect to the remote server
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 
can you help me in this.

**Comment by andris9** [comment]
I'd suggest you to use WildDuck installer that also installs and sets up ZoneMTA. You can build your own configuration on top of that setup. https://github.com/nodemailer/wildduck/tree/master/setup

**Comment by Manishjodhani** [comment]
Hi andris9,
i have try but....i have centos and install scripts for ubuntu.
can you please give me scripts for centos server.
