### ISSUE TITLE
can i use multiple domain and multiple IPs ?

### ISSUE THREAD

**Issue by martandya** [zone-eu/zone-mta#105]
Hello Sir,

I just successfully create services with wild duck, i have setup as per you give install script and same successes.
well i just wanted to integrate it my production lavel server like i have server with 1000 IP and 100 domains so can i able to configure the server with multiple IPs and multiple domains ?
For example i have 100 domain and 1000 IPs on the server so i wanted to assign 10 IP per domain with IP rotation and each domain with own email header ?
Is that Possible ...
Can i rotate IPs ?
if yes then where is detailed documentation ?
if not then please guide me to getting start ...

Thank You.

**Comment by andris9** [comment]
You would have to write plugins for custom handling. Here's an example plugin for setting specific local IP address for a specific domain: [custom-ip.js](https://gist.github.com/andris9/1f7be37570082e02d8496388d01d49cf)
