### ISSUE TITLE
Queue counter mongo query - full index scan

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#106]
The queue counter mongo query does every time a full index scan because it uses: `$ne` operator.

```javascript
query: { sendingZone: { $ne: false }, queued: { $lte: new Date(1517931968511) } }
```

Can we improve this ?

**Comment by andris9** [comment]
I removed `sendingZone` argument from the query and added separate index for `queued`. `sendingZone` was only included to use a index with {sendingZone, queued, ...} but I guess that using $ne did not work well with this intention. Upgrading ZoneMTA to v1.6.0 should fix this.
