### ISSUE TITLE
How can i sent test mail ?

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#107]
Hi ,
How should i know my zonemta is working or not ?.
How can i send a test mail through zone-mta ?
please tell me anyone??????

**Comment by andris9** [comment]
If ZoneMTA is properly configured then you should have a SMTP/MSA interface listening on port 587. Use any SMTP client to send out an email through that port.

**Comment by Manishjodhani** [comment]
Hello sir, Now my admin panel has open.
But how can i send the messages in admin panel
