### ISSUE TITLE
how can i authenticated SMTP server ??

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#108]

**Comment by Manishjodhani** [comment]
Is anyone there how can tell me how authenticate the smtp in zone-mta.???
I'm very new to zone-mta please tell me

**Comment by andris9** [comment]
You can create your own authentication login with plugins. See example: https://gist.github.com/andris9/938a73247b1e76ec515293f580dfa802

**Comment by Manishjodhani** [comment]
i find this error after editing on that file..
ERR! Plugins Failed loading plugin file <plugins/authplugin>: Cannot find module '/root/download/zone-mta-template/plugins/authplugin'

**Comment by Manishjodhani** [comment]
Hi andris9
Can you tell me solved this error
