### ISSUE TITLE
[OT] Help with MTA forward configuration

### ISSUE THREAD

**Issue by ericchaves** [zone-eu/zone-mta#109]
Hi Folks,

I'm running ZoneMTA (using docker-compose) locally on my machine in order to test some configurations. In order to prevent ZoneMTA to actually send any message I'm trying to configure the default zone to forward all messages to a second MTA which is actually a [mailhog](https://github.com/mailhog/MailHog) linked container listening on port 1025.

For that I'm using this  `config/zones/default.toml` is:
```
[default]
preferIPv6=false
ignoreIPv6=true
processes=1
connections=5
host="mailhog"
port=1025
pool="default"
logger=true
logLevel="silly"
```
An in order to test this setup I'm trying to send a message to an invalid MX domain (hotmail.com.br) but instead of passing the message to my local mailhog ZoneMTA is trying to deliver the message to the actual IP of hotmail.com.br on the 1025 port as per the following docker  log.

```
zonemta_1    | info Sender/default/22[1] Created sender instance
zonemta_1    | verb Queue 1618c997996000aec9.001 SHIFTED (key="lock 1618c997996000aec9 001" zone="default")
zonemta_1    | verb Sender/default/22[1] 1618c997996000aec9.001 FETCHED for delivery (from=postmaster@example.net.br to=test@hotmail.com.br)
zonemta_1    | info Sender/default/22[1] 1618c997996000aec9.001 CONNECTING domain=hotmail.com.br port=1025
zonemta_1    | info Sender/default/22[2] Created sender instance
zonemta_1    | info Sender/default/22[3] Created sender instance
```
What am I doing wrong? How should I configure my default pool to deliver all messages to mailhog?

Thanks in advance,

Eric.

**Comment by andris9** [comment]
Here's a [plugin for using custom routing](https://gist.github.com/andris9/7114ae3dd400a0eccd0d8c3a3a112933) logic. In short it predefines a MX resolver result, so MX resolving is skipped for that delivery and whatever is provided is used for creating the connection.
