### ISSUE TITLE
450-prevents additional messages from being delivered 

### ISSUE THREAD

**Issue by vijay-thakur** [zone-eu/zone-mta#110]
Hi,
How can I increase rate limit to deliver messages to email addresses. Actually Its failing for one of the address, Not able to send and its giving these errors :-->
450-4.2.1 450-4.2.1 The user you are trying to contact is receiving mail at a rate that
450-prevents additional messages from being delivered. Please resend your
450-message at a later time. If the user is able to receive mail at that

How can change this limit so that i can send more messages without getting these errors.
Please Reply.
Thanks

**Comment by yeya** [comment]
The issue is not in your server, the  recipient getting to many emails, not specifically from you.
Check this [answer](https://stackoverflow.com/a/44895081/3107689)
