### ISSUE TITLE
Enhancement : Delivery Status Updates.

### ISSUE THREAD

**Issue by nadarkathiresh** [zone-eu/zone-mta#111]
I went through the documentation, i dont see an option where zonemta can push Delivery status updates into some queue ( Redis queue), so that the transaction can be updated into a database.

There seems to be an API for pulling the info, but is there a way to push the info from Zonemta to any queueing database.

**Comment by andris9** [comment]
You can use the 'log:entry' hook like it is done [here](https://github.com/nodemailer/zonemta-wildduck/blob/1a27ef9ff5020aaaa1b1032deb557525bba7e7ca/index.js#L458-L461) to catch information about messages
