### ISSUE TITLE
/usr/sbin/sendmail replacement

### ISSUE THREAD

**Issue by szepeviktor** [zone-eu/zone-mta#112]
Hello!

I am new to Zone MTA. After finding no reference to replacing `/usr/sbin/sendmail`:
Are there plans to have a CLI command that would act like a shim for sendmail?

**Comment by yeya** [comment]
If your goal is only to have all the ZoneMTA extra features - You don't have to replace it, just configure sendmail to use ZoneMTA as smtp host.

**Comment by andris9** [comment]
No plans for a sendmail replacement at this moment.

**Comment by szepeviktor** [comment]
Okay.
