### ISSUE TITLE
SMTP authentication is possible ???

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#117]
Hello ,
is there any way to use secure smtp in zonemta like username and password????

**Comment by andris9** [comment]
You can use the example authentication plugin: https://gist.github.com/andris9/938a73247b1e76ec515293f580dfa802

**Comment by Manishjodhani** [comment]
I have done that but still don't working
please check the screen shot...
![screenshot_11](https://user-images.githubusercontent.com/28861157/37651892-a7b83b9e-2c5f-11e8-94bf-95cae8061f4c.png)

**Comment by andris9** [comment]
You need to store the plugin file as /root/zone-mta-template/plugins/authplugin.js
