### ISSUE TITLE
Can we add more than one dkim records???

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#118]
Hello,
I try to add more one domain in zone-mta but there is problem with Dkim records.
How can we add more than one dkim records for more than one domains???

**Comment by andris9** [comment]
For any custom logic you need to create your own plugins and not use the default ones. For DKIM you can use the example dkim plugin and then edit it for your own use case (Eg. if sender is x then use dkim key y, if sender is z then use dkim key w) https://gist.github.com/andris9/ef6e0f9014b6502077cf2d938412f400

**Comment by Manishjodhani** [comment]
info Sender/bounces/2609[1] 162482cd4240003fdf.001 CONNECTING domain=rccess.tech port=25
ERR! Sender/bounces/2609[1] 162482cd4240003fdf.001 ERRCONNECT domain=rccess.tech error=DNS error when resolving MX server for rccess.tech: DNS server returned answer with no data
info Sender/bounces/2609[1] 162482cd4240003fdf.001 REJECTED[recipient] from=<> to=info@rccess.tech src= dst=rccess.tech id=<ef88ce87-abf9-edd0-46f8-f45efcdd8e2b@manage> (550 DNS error when resolving MX server for rccess.tech: DNS server returned answer with no data)
verb Queue Deleting unreferenced message 162482cd4240003fdf
verb Queue 162482cd4240003fdf REMOVE
can what is problem in thsi error...???

**Comment by andris9** [comment]
Read the error message: error=DNS error when resolving MX server for mydomain: DNS server returned answer with no data

**Comment by Manishjodhani** [comment]
(Eg. if sender is x then use dkim key y, if sender is z then use dkim key w) https://gist.github.com/andris9/ef6e0f9014b6502077cf2d938412f400
where should i create this config.json file ....???

**Comment by andris9** [comment]
The config file is not relevant. The javascript code shows you the basics of how to use dkim signing, what you need to do is to take that code and modify it by implementing your own logic for selecting keys. For example you can check out how it is handled by wildduck-zonemta plugin [here](https://github.com/nodemailer/zonemta-wildduck/blob/1a27ef9ff5020aaaa1b1032deb557525bba7e7ca/index.js#L400-L456)

**Comment by Manishjodhani** [comment]
Ok....now i got it.
Thank You
