### ISSUE TITLE
Where are the bounce details are stored???

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#119]
Hello,
![screenshot_13](https://user-images.githubusercontent.com/28861157/37696580-c913483a-2cfd-11e8-813c-e69e0310c86e.png)
Please tell me where i get this bounced =526 details 
when i click on bounce then it show me this
![screenshot_14](https://user-images.githubusercontent.com/28861157/37696624-1a769358-2cfe-11e8-8fea-02351222e66e.png)
Please tell me???

**Comment by andris9** [comment]
These are statistical counters. It means that 526 messages were rejected, 524 bounce responses were generated and it was not possible to deliver these. See the server logs for more details

**Comment by Manishjodhani** [comment]
I can not find the logs can,you please tell me details..???Where should i find them...???

**Comment by andris9** [comment]
It depends how you installed the app. Normally the logs should be found from syslog.

**Comment by Manishjodhani** [comment]
I want to delete the active bounce records. How can i do that???
i can't access to db it show this.
> show dbs
admin     0.000GB
local     0.000GB
logs      0.000GB
zone-mta  0.155GB
> use zone-mta
switched to db zone-mta
> show collections
mail.chunks
mail.files
suppressionlist
zone-queue
> db.zone-queue.find()
 E QUERY    [thread1] ReferenceError: queue is not defined :
@(shell):1:1

**Comment by elmehdiabdi-src** [comment]
the calcs and counters its stored at redis database
