### ISSUE TITLE
Sending Zone for sending bounce messages

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#120]
Hello,
this in config.js
// Sending Zone for sending bounce messages
        bounces: {
            preferIPv6: false,
            ignoreIPv6: true,
            connections: 1,
            processes: 1,
            //zone specific logging
            //logger: true,
            //logLevel: 'silly'

            // * send through next MTA instead of MX
            port: 110,
            host: 'MyBounceServer',
             auth: { // optional
                user: 'postmaster@mydomain',
                pass: 'password'
            }
            pool: 'default'
        }
**ERROR**:
![screenshot_15](https://user-images.githubusercontent.com/28861157/37709391-11a588b0-2d30-11e8-9473-578a4da78973.png)
And this log file
![screenshot_16](https://user-images.githubusercontent.com/28861157/37709498-68751890-2d30-11e8-8fe9-5b8173422cee.png)

Any body please tell me how to solve this error...???

**Comment by amitsquare** [comment]
What exactly is your problem ?
configuring bounce zone Or starting zone-mta ?

**Comment by Manishjodhani** [comment]
configure the bounce  zone

**Comment by andris9** [comment]
Configuration syntax seems invalid, there's a comma missing
