### ISSUE TITLE
Installing in Centos 6.9 ??

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#121]
[zone-mta-template]# npm install --production

> modern-syslog@1.1.4 install /root/zone-mta-template/node_modules/modern-syslog
> node-gyp rebuild

make: Entering directory `/root/zone-mta-template/node_modules/modern-syslog/build'
  CXX(target) Release/obj.target/core/core.o
In file included from ../core.cc:2:
../../nan/nan.h:47:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /root/.node-gyp/9.9.0/include/node/v8.h:21,
                 from /root/.node-gyp/9.9.0/include/node/node.h:63,
                 from ../core.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /root/.node-gyp/9.9.0/include/node/node.h:63,
                 from ../core.cc:1:
/root/.node-gyp/9.9.0/include/node/v8.h: At global scope:
/root/.node-gyp/9.9.0/include/node/v8.h:335: error: expected unqualified-id before ‘using’
/root/.node-gyp/9.9.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/9.9.0/include/node/v8.h:352: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/9.9.0/include/node/v8.h:359: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/9.9.0/include/node/v8.h:367: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/root/.node-gyp/9.9.0/include/node/v8.h:396: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/root/.node-gyp/9.9.0/include/node/v8.h:398: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/root/.node-gyp/9.9.0/include/node/v8.h:403: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/9.9.0/include/node/v8.h:443: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/9.9.0/include/node/v8.h:777: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/9.9.0/include/node/v8.h:802: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/9.9.0/include/node/v8.h:814: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: At global scope:
/root/.node-gyp/9.9.0/include/node/v8.h:840: error: expected unqualified-id before ‘using’
/root/.node-gyp/9.9.0/include/node/v8.h:1237: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h:1243: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/root/.node-gyp/9.9.0/include/node/v8.h:1793: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: At global scope:
/root/.node-gyp/9.9.0/include/node/v8.h:2505: error: ISO C++ forbids declaration of ‘constexpr’ with no type
/root/.node-gyp/9.9.0/include/node/v8.h:2505: error: expected ‘;’ before ‘int’
/root/.node-gyp/9.9.0/include/node/v8.h:3260: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/9.9.0/include/node/v8.h:3901: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/9.9.0/include/node/v8.h: At global scope:
/root/.node-gyp/9.9.0/include/node/v8.h:4170: error: function definition does not declare parameters
/root/.node-gyp/9.9.0/include/node/v8.h:4224: error: expected unqualified-id before ‘&’ token
/root/.node-gyp/9.9.0/include/node/v8.h:4224: error: expected ‘)’ before ‘&’ token
/root/.node-gyp/9.9.0/include/node/v8.h:4224: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from /root/.node-gyp/9.9.0/include/node/v8-platform.h:11,
                 from /root/.node-gyp/9.9.0/include/node/node.h:64,
                 from ../core.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/core/core.o] Error 1
make: Leaving directory `/root/zone-mta-template/node_modules/modern-syslog/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.87-xxxx-std-ipv6-64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/zone-mta-template/node_modules/modern-syslog
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 (node_modules/modern-syslog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@1.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

How to solve this problem ????

**Comment by andris9** [comment]
It's an optional dependency. Everything should work fine even if you not manage to compile it
