### ISSUE TITLE
how to add ip pools???

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#122]
I have 2 ip range list but i don't how apply them in zonemta ??
how to add ip pools ??

**Comment by amitsquare** [comment]
Look at the Pools & zones setting.
Very easy to do .

**Comment by Manishjodhani** [comment]
May you please tell me where should i look???

**Comment by Manishjodhani** [comment]
i do some changes but it's not working
![screenshot_17](https://user-images.githubusercontent.com/28861157/37960632-bb337d72-31d3-11e8-928e-5649fadf4743.png)

![screenshot_18](https://user-images.githubusercontent.com/28861157/37960637-bd2bb572-31d3-11e8-83d9-778df7fa3336.png)

Have a look

**Comment by Manishjodhani** [comment]
Hi @amitsquare  can you tell me where is the problem in conf file ???
