### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#124]
![screenshot_19](https://user-images.githubusercontent.com/28861157/38027802-956b1132-32ae-11e8-8a40-4a567dfd5e14.png)

Suddenly stop...Is there any solution for this????

**Comment by andris9** [comment]
Please try to gather more information before creating a support issue. No-one knows why it stopped.

**Comment by Manishjodhani** [comment]
ok...next time i will provide all information.
How to run zonemta in background???
