### ISSUE TITLE
Zonemta Installs?

### ISSUE THREAD

**Issue by longhorninmd** [zone-eu/zone-mta#125]
Does anyone on here do zonemta installs?  If so, are possibly on Upwork too?

**Comment by andris9** [comment]
Hey Russell, are you trying to set up a test instance of ZoneMTA? Contact me off list andris.reinman@gmail.com

**Comment by gacott** [comment]
I have emailed you as well @andris9

**Comment by longhorninmd** [comment]
Unfortunately, no response...

**Comment by gacott** [comment]
Oh, not you either @longhorninmd ? I figured it was just me. :-(  Working with Postal myself right now. Liked what ZoneMTA sounded like but need a little help for sure.

**Comment by longhorninmd** [comment]
I'm using Postal too.

**Comment by andris9** [comment]
@longhorninmd I never received any message from you and if it went to spam then by now it is long gone from there :S

@gacott I tried to find your message after your first comment but was not able to identify anything either, nothing from your username, did you send it by using another name? I get tons of emails and most just gets buried

**Comment by longhorninmd** [comment]
<img width="203" alt="screen shot 2018-05-29 at 9 56 28 pm" src="https://user-images.githubusercontent.com/133784/40694565-34230df4-638b-11e8-97e8-c79bb765d453.png">

**Comment by dazoot** [comment]
Can we close this ?
