### ISSUE TITLE
How to run zonemta in background???

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#126]
Hi,
I need to run zonemta in background ??

**Comment by andris9** [comment]
Check out Wildduck mail server install script as it creates a systemd service for ZoneMTA https://github.com/nodemailer/wildduck/blob/master/setup/install.sh

**Comment by Manishjodhani** [comment]
how can i run zonemta in Daemonize mode???

**Comment by andris9** [comment]
zonemta does not handle daemonizing itself, you need to run it as a [systemd service](https://github.com/zone-eu/zone-mta/blob/master/setup/zone-mta.service) or use standard tools like nohup etc.
