### ISSUE TITLE
zone host / port + auth not working

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#127]
I am trying to set a zone (not bounce) to send via a remote, smtp + port + auth data.

// port: 587,
            // host: 'smtp.gmail.com',
            // auth: { // optional
            //    user: 'username@gmail.com',
            //    pass: 'ssssss'
            //}

It does not seem to work.
It tries to do authentication but to the wrong host / port.
It seems it's trying to connect to the MX host.

**Comment by andris9** [comment]
This should be fixed in v1.7.2

**Comment by afeyavari** [comment]
Dear andris

My team made some changes on ZoneMTA , Which file should update to fix this issue ?
