### ISSUE TITLE
Queue server closed unexpectedly ???

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zone-mta#128]
RangeError [ERR_INVALID_ASYNC_ID]: Invalid asyncId value: -2147483645
    at validateAsyncId (internal/async_hooks.js:116:16)
    at emitBeforeScript (internal/async_hooks.js:318:3)
    at process._tickCallback (internal/process/next_tick.js:97:9)
ERR! Sender/default/2034 Connection to Queue server closed unexpectedly
ERR! SMTP/feeder/2114 Connection to Queue server closed unexpectedly
ERR! Sender/default/2104 Connection to Queue server closed unexpectedly
ERR! Sender/default/1972 Connection to Queue server closed unexpectedly
???

**Comment by dazoot** [comment]
Seems some internal network configuration issue. 
Close ?
