### ISSUE TITLE
XCLIENT support

### ISSUE THREAD

**Issue by waszi** [zone-eu/zone-mta#133]
It would be great to add support for XCLIENT. smtp-server library supports it so it shouldn't be very difficult to add. For the moment "useXClient: true" in lib/smtp-interfaces.js is doing the job.

**Comment by andris9** [comment]
Published zone-mta v1.7.1. You can now use the additional SMTPServer options in the smtp interface [configuration block](https://github.com/zone-eu/zone-mta/blob/4f36c4af4085ede95d5cbe49e03ed36c37cec2ba/config/default.js#L209-L216)

**Comment by andris9** [comment]
Btw, are you just testing ZoneMTA out or are you using it production somewhere?

**Comment by waszi** [comment]
I am currently working to replace Haraka on production.  We are currently using Haraka as shared hosting MTA. Initial tests are very promising, especially zones/ip pools that works out of the box.

We use nginx as frontend proxy with Golang based authenticator (rate limits, access-list, anti-bruteforce etc) . XCLIENT allows us to pass user information to backend. We have to dynamically assign user to his zone. Basic hosting plan is using shared IP Pool, premium offer comes with dedicated IP.

**Comment by andris9** [comment]
Just a note, ZoneMTA does not allow live config updates for zones and such, so I'd suggest you to create a plugin for your premium users that selects their account specific dedicated IP instead of using dedicated zones. This way you would have two pools - one for basic plan and one for premium. The basic plan zone would select from the available IP pool, for the premium users the plugin would select correct IP.

Such a plugin would look like this:

```javascript
module.exports.init = function(app, done) {
    app.addHook('sender:fetch', (delivery, next) => {
        if(delivery.sendingZone !== 'premium'){
        	// ignore non-premium plan messages, use default address
        	return next();
        }

        // somehow resolve the user of the delivery and the IP to use
        let ipdata = database.resolveIpForUser(delivery.user)

        // set for the local address to use for this delivery
        delivery.zoneAddress = {
            address: ipdata.address, //'1.2.3.4'
            name: ipdata.hostname // 'dedicated.address.hostname'
        };
        next(); 
    });
    done();
};
```
