### ISSUE TITLE
zone hang after mongo server upgrade

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#135]
We ran into a weird BUG.

After a mongo upgrade one of the defined zones stopped working.

Error in log looks like this:
```
zone-mta[22034]: (Sender/z1/22034[4]) 162ce89ba970008296.001 FETCHFAIL [bkdZmKBlkY] error=interrupted at shutdown
```

After:
```
Apr 17 19:18:14 server zone-mta[22103]: (Sender/z1/22103) [d53dee61f166a699f160] Starting sending for z1
Apr 17 19:19:14 server zone-mta[9281]: (Child/z1/22103) Sender process d53dee61f166a699f160 for z1exited with 1
Apr 17 19:19:20 server zone-mta[22593]: (Sender/z1/22593) [9d1131d26ce58d35e1f8] Starting sending for z1
Apr 17 19:20:20 server zone-mta[9281]: (Child/z1/22593) Sender process 9d1131d26ce58d35e1f8 for z1exited with 1
Apr 17 19:20:26 server zone-mta[25020]: (Sender/z1/25020) [e9b2b91facb1028c0887] Starting sending for z1
Apr 17 19:21:26 server zone-mta[9281]: (Child/z1/25020) Sender process e9b2b91facb1028c0887 for z1exited with 1
```

**Comment by dazoot** [comment]
I think i had 1.6.2 (not the latest one). It's odd that the other zones kept working fine after.

**Comment by andris9** [comment]
How did this happen anyway, did you upgrade Mongo without restarting zone-mta in between, or did you stop both or what? Did restarting zone-mta resolve that issue or is it still failing?

**Comment by dazoot** [comment]
I was upgrading Mongo without restarting ZoneMTA. After restarting ZoneMTA, all is ok.

**Comment by andris9** [comment]
Seems like some kind of race condition that was triggered during the mongo reconnect. Really hard to say what actually happened there, I went through the code and found nothing obviously wrong. Maybe if it happens again then there's more info or ways to reproduce.
