### ISSUE TITLE
Outbound send not using all connections

### ISSUE THREAD

**Issue by Etharin** [zone-eu/zone-mta#141]
When sending a list of 2000 emails we're seeing some odd behaviour with 2 sending zones where each sending zone only seems to pick up between 4 and 7 emails despite being set to use 2 processes and 10 connections. The maxConnections for the default domain has been set to 40 which should allow all connections to send even if they're to the same domain. We're unsure of why there would be a limit, do named zones not respect the maxConnections setting? As you can see from the timings below every 5 seconds the named i574 queue picks up 5 emails. The domain config is:

     domainConfig: {
        // default is required
        default: {
            // How many parallel connections per Sending Zone to use against a recipient domain
            maxConnections: 25,
            // blacklisted IP addresses that should not be used to send mail to this specific server
            disabledAddresses: []
        }

Is there something we're missing?

> May 21 08:59:43 zonemtapoc zone-mta[27089]: (Sender/i574/27089[4])
May 21 08:59:43 zonemtapoc zone-mta[27054]: (Sender/i574/27054[4])
May 21 08:59:43 zonemtapoc zone-mta[27089]: (Sender/i574/27089[2])
May 21 08:59:43 zonemtapoc zone-mta[27089]: (Sender/i574/27089[1])
May 21 08:59:43 zonemtapoc zone-mta[27089]: (Sender/i574/27089[9])
May 21 08:59:47 zonemtapoc zone-mta[27043]: (Sender/default/27043[5])
May 21 08:59:47 zonemtapoc zone-mta[27083]: (Sender/default/27083[7])
May 21 08:59:47 zonemtapoc zone-mta[27043]: (Sender/default/27043[8])
May 21 08:59:47 zonemtapoc zone-mta[27043]: (Sender/default/27043[2])
May 21 08:59:47 zonemtapoc zone-mta[27083]: (Sender/default/27083[2])
May 21 08:59:48 zonemtapoc zone-mta[27054]: (Sender/i574/27054[9])
May 21 08:59:48 zonemtapoc zone-mta[27089]: (Sender/i574/27089[8])
May 21 08:59:48 zonemtapoc zone-mta[27054]: (Sender/i574/27054[1])
May 21 08:59:48 zonemtapoc zone-mta[27089]: (Sender/i574/27089[5
May 21 08:59:48 zonemtapoc zone-mta[27054]: (Sender/i574/27054[5])
May 21 08:59:52 zonemtapoc zone-mta[27083]: (Sender/default/27083[5])
May 21 08:59:52 zonemtapoc zone-mta[27043]: (Sender/default/27043[3])
May 21 08:59:52 zonemtapoc zone-mta[27043]: (Sender/default/27043[9])
May 21 08:59:52 zonemtapoc zone-mta[27083]: (Sender/default/27083[10])
May 21 08:59:52 zonemtapoc zone-mta[27043]: (Sender/default/27043[1])
May 21 08:59:53 zonemtapoc zone-mta[27054]: (Sender/i574/27054[8
May 21 08:59:53 zonemtapoc zone-mta[27089]: (Sender/i574/27089[10])
May 21 08:59:53 zonemtapoc zone-mta[27054]: (Sender/i574/27054[2])
May 21 08:59:53 zonemtapoc zone-mta[27054]: (Sender/i574/27054[10])
May 21 08:59:53 zonemtapoc zone-mta[27054]: (Sender/i574/27054[7])
May 21 08:59:57 zonemtapoc zone-mta[27043]: (Sender/default/27043[6])
May 21 08:59:57 zonemtapoc zone-mta[27083]: (Sender/default/27083[1])
May 21 08:59:57 zonemtapoc zone-mta[27083]: (Sender/default/27083[6])
May 21 08:59:57 zonemtapoc zone-mta[27083]: (Sender/default/27083[8
May 21 08:59:58 zonemtapoc zone-mta[27043]: (Sender/default/27043[4])
May 21 08:59:58 zonemtapoc zone-mta[27089]: (Sender/i574/27089[7])
May 21 08:59:58 zonemtapoc zone-mta[27089]: (Sender/i574/27089[3])
May 21 08:59:58 zonemtapoc zone-mta[27054]: (Sender/i574/27054[3])
May 21 08:59:58 zonemtapoc zone-mta[27089]: (Sender/i574/27089[6])
May 21 08:59:58 zonemtapoc zone-mta[27054]: (Sender/i574/27054[6])
May 21 09:00:03 zonemtapoc zone-mta[27083]: (Sender/default/27083[9])
May 21 09:00:03 zonemtapoc zone-mta[27083]: (Sender/default/27083[3])
May 21 09:00:03 zonemtapoc zone-mta[27083]: (Sender/default/27083[4])
May 21 09:00:03 zonemtapoc zone-mta[27083]: (Sender/default/27083[7
May 21 09:00:03 zonemtapoc zone-mta[27043]: (Sender/default/27043[10])
May 21 09:00:03 zonemtapoc zone-mta[27054]: (Sender/i574/27054[4])
May 21 09:00:03 zonemtapoc zone-mta[27089]: (Sender/i574/27089[1])
May 21 09:00:03 zonemtapoc zone-mta[27089]: (Sender/i574/27089[2])
May 21 09:00:03 zonemtapoc zone-mta[27054]: (Sender/i574/27054[9])
May 21 09:00:03 zonemtapoc zone-mta[27089]: (Sender/i574/27089[4])
May 21 09:00:08 zonemtapoc zone-mta[27043]: (Sender/default/27043[5])
May 21 09:00:08 zonemtapoc zone-mta[27043]: (Sender/default/27043[7])
May 21 09:00:08 zonemtapoc zone-mta[27043]: (Sender/default/27043[8])
May 21 09:00:08 zonemtapoc zone-mta[27083]: (Sender/default/27083[2])
May 21 09:00:08 zonemtapoc zone-mta[27043]: (Sender/default/27043[3])
May 21 09:00:08 zonemtapoc zone-mta[27083]: (Sender/default/27083[5])
May 21 09:00:08 zonemtapoc zone-mta[27043]: (Sender/default/27043[9])

**Comment by andris9** [comment]
How much time does it taeks to send a single message? Are the messages already in queue when you started the server or were you feeding the messages to the server in parallel while sending?

**Comment by Etharin** [comment]
A single message also takes around 2 seconds from fetching to SMTP close. When sending multiples it seems to take around the same amount of time but it doesn't go and pick up another message straight away and all the threads don't seem to pick up messages. 
The messages are added via the SMTP interface, we can add 2000 in around 15 seconds with 10 processes. This doesn't seem to affect the sending speed as we don't add any more messages after that 2000 batch.

**Comment by andris9** [comment]
You could try to change the limits, for example like this:

zone:

* processes=3
* connections=6
* throttling=false

domainConfig:

* maxConnections=18

**Comment by Etharin** [comment]
Hi Andris, sorry for the delay in getting back to you. I've tried those settings and it's still sending in batches of 5. Is there any limitation in redis/mongo that could be causing it?

**Comment by visomymail** [comment]
can you help to set up and set up a zone for work for payment? It is very necessary, can not understand.

**Comment by dazoot** [comment]
Close here too ? 

If the message takes 2 second to fetch from SMTP try upgrading infrastructure (more RAM / CPU / SSD / network) for mongo. Usually the DB is the main bottleneck, not zonemta.
