### ISSUE TITLE
clarify: how does throttling work ?

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#144]
This is not an actual issue, but a question.

How does throttling work ?
For a zone we have:
```
connections = 5
processes = 5
```

The number of simultaneous connection is per ZONE or per zone PROCESS ?
What about domain maxConnections? Is it calculated per ZONE, per zone PROCESS ?

**Comment by andris9** [comment]
The throttling feature is kind of immature as I never needed myself. It is calculated per connection, so if you have 5 processes and 5 connections with throttling 1 message per second then it actually means 25 messages per second for the entire zone. I don't think the feature is actually useful as it is today.
