### ISSUE TITLE
Route all outgoing mails through another relay

### ISSUE THREAD

**Issue by atikulhaider** [zone-eu/zone-mta#145]
**Hi,**
I'm a beginner.
I can't figure out how to configure external relay for all outgoing mail. Here is what I want: [http://www.postfix.org/postconf.5.html#relayhost](url)
Like postfix _relayhost_, I want to route all my outgoing mails through another relay, say through an Cloud Antispam gateway.
On postfix, if I add just this line: `relayhost = relay.symantec.com:25` all done.
How can I achieve this with ZoneMTA please? I have followed this [https://gist.github.com/andris9/7114ae3dd400a0eccd0d8c3a3a112933](url) and moved **customrouter.js** to _plugins_ folder & **customrouter.toml** to _config/plugins_ folder. Then added the lines below to _production.json_ file inside plugins:
`"customrouter": {
            "enabled": ["sender"],
            "host": "relay.symantec.com",
            "port": 25`
Doesn't work as I can't figure it out. Please help me.

**Comment by andris9** [comment]
You can ignore the customrouter example. Upgrade zone-mta to latest and add “host” option to the sending zone settings that should point to your next hop MTA

**Comment by atikulhaider** [comment]
Thank you so much :) You're a legend!
It worked like a charm! :+1:
