### ISSUE TITLE
How to deal with ips with network timeout

### ISSUE THREAD

**Issue by jquequezana** [zone-eu/zone-mta#146]
Hello 

Im using the zone-mta with several ip pools, sometimes I get network timeout from the "mx-connect" module with some ip segments would like know how can deal with that and disable that ips for some time or forever.... (on the fly) 
I know I need put some code... but only trying to know how you can deal with that...

Regards

**Comment by andris9** [comment]
ZoneMTA expects network to be reliable, if your IP addresses do not actually work, then remove these from config and restart ZoneMTA service
