### ISSUE TITLE
Sending Zone spanning multiple instances?

### ISSUE THREAD

**Issue by erickpece** [zone-eu/zone-mta#149]
Is it possible to have a Sending Zone span multiple instances?

For example, if we have 5 instances on different servers, each with 2 IP addresses, for a total of 10 IP's, could we split those into 2 different Sending Zones?

Then, if a message comes in destined for the first zone, ZoneMTA would route to the appropriate server?

Alternately, can ZoneMTA route messages through a proxy instead?

**Comment by erickpece** [comment]
Fantastic!  As a follow-up, when passing in the message via API, if we have the same Sending Zone spanning these hosts, do we have to pass the message to the instance with the IP we want for a given message, or would ZoneMTA automatically reroute to a different instance?

**Comment by andris9** [comment]
If you have several instances servicing the same zone then a message pushed to this zone ends up in a random instance (except for the deferred messages - to use the same IP the message ends up in the same instance it was handled by the first time)
