### ISSUE TITLE
Multi zoneMTA VPS and one redis/mongo

### ISSUE THREAD

**Issue by victorbrunetti** [zone-eu/zone-mta#150]
I made this diagram to better explain my doubt;
https://i.paste.pics/d0964d76859ade903ac4143250f87e6a.png

Assuming I have 1500 recipients for gmail and another 1500 recipients for other domains.

Following the diagram,
VPS 2 will deliver + - 250 emails per hour to gmail and 250 more to other domains.
VPS 3 will deliver + - 850 emails per hour to gmail and 850 more to other domains.
VPS 4 will deliver +/- 150 emails per hour to gmail and over 150 to other domains.
VPS 5 will deliver + - 350 emails per hour to gmail and 350 more to other domains.

Is this my logic correct?

1 vps will have the redis and mongodb and other vps will have the zoneMta.
Everyone will have
connections: 1
processes: 1
and only 1 IP each.

**Comment by andris9** [comment]
It should work like you described even though throttling might not work reliably if you use per hour metrics, it was more designed to handle per-second limits, eg 10 messgaes per second. Messages are not equally divided between the given hour but as many messages are sent as possible until you hit the throttling limit. So if you have 100 messages per hour and you try to send 120 messages, then the server probably delivers 100 messages in the first second and then waits the entire hour to deliver the next 20.
