### ISSUE TITLE
admin cant see history list

### ISSUE THREAD

**Issue by u007** [zone-eu/zone-mta#152]
hi,

i cant seems to see the history in admin dashboard.
it indicate the number of emails per domain
and it shows ques with some numbers, but clicking into it, and both tab active and deferred is empty

is this working as intended?

**Comment by u007** [comment]
hi @andris9 andris,
after running awhile, i realize all default and bounces count are reset to 0
including top destinations todays.

does it mean that all count will be reset on daily basis?
how do i retain those count for min 60days?

thank you

**Comment by andris9** [comment]
The admin console logs everything into "buckets" in Redis with todays date in key name (in UTC), so the data is still there but you just don't see it.

For example if you want to see how many messages were delivered and bounced in 2018/06/04 and which were the top domains you can check this from Redis:

```
127.0.0.1:6379[2]> GET frwrdr_delivered^2018/06/04
"456789"
127.0.0.1:6379[2]> GET frwrdr_bounced^2018/06/04
"12678"
127.0.0.1:6379[2]> zrevrange frwrdr_domains^2018/06/04 0 10 WITHSCORES
 1) "gmail.com"
 2) "123456"
 3) yahoo.com"
 4) "2345"
 5) "hotmail.com"
 6) "2333"
    ...
```

**Comment by u007** [comment]
okay thank you :)
