### ISSUE TITLE
haproxy proxy protocol support

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#156]
Does zonemta support `proxy` protocol from haproxy ?

Ex: in postfix we have:
`smtpd_upstream_proxy_protocol=haproxy`

I see in the code `useProxy`. Is this implemented ?

**Comment by andris9** [comment]
Yes, Haproxy is supported. Just set `useProxy=true` to the settings of any SMTP interface (eg. into [this block](https://github.com/zone-eu/zone-mta/blob/master/config/default.js#L182-L229)) you want to use with it.

You can also use Nginx XClient in a similar way (`useXClient` setting)

**Comment by rhclayto** [comment]
It appears this doesn't work properly. See https://github.com/zone-eu/zone-mta/issues/167#issuecomment-436866492
