### ISSUE TITLE
Question: Is possible to override configuration with environment variables?

### ISSUE THREAD

**Issue by lukasmrtvy** [zone-eu/zone-mta#160]
Is possible to override configuration with environment variables?
For future Docker images should be possible to somehow override config settings.
It should be possible to read env variables, if not specified then fallback to variables from config files.
Thanks

**Comment by dazoot** [comment]
I think you can change the path to the config file from the node argument.

`node index.js --config=/etc/zonemta/zonemta.toml`

There is no way to override config variables from the environment.

Close ?

**Comment by andris9** [comment]
You can also use command line arguments to override configuration. Use dot notation for subkeys

```
$ node index.js --dbs.mongo="mongodb://127.0.0.1:27017/zone-mta" --dns.caching=false
```
