### ISSUE TITLE
421 4.4.1 Connection timed out. Total session duration: 00:05:00.7054661

### ISSUE THREAD

**Issue by bunyevacz** [zone-eu/zone-mta#161]
Hi,

We have a partner whos smtp server is slow. 
I checked with mtoolbox.com website, and the smtp transaction time is:  8.173 seconds

The log contains the following:
```
65311b138000c923.001 SMTPCLOSE [OQHJJhWtKo] Connection closed response="421 4.4.1 Connection timed out. Total session duration: 00:05:00.7054661"
```

zone-mta tries to deliver each 4 hours, but never succeeds (well, it tried 8 times already, 32 hours in total).

My question is, where can I lift the limit to 20 seconds from 5 seconds?

I tried to dig into the sourcecode ([lib/sender.js:222][0]): 

```
 log.info(
                                    this.logName,
                                    '%s.%s SMTPCLOSE [%s] Connection closed response="%s"',
                                    delivery.id,
                                    delivery.seq,
                                    connection.id,
                                    connection.lastServerResponse || ''
                                );
```

But I do not find what generates the `lastServerResponse`.

On line [166][1], there is a hardcoded 10 sec timeout, I do not know if it is related, seems like in my case the timeout is 5 second.

Any help is much appreciated.

[0]: https://github.com/zone-eu/zone-mta/blob/master/lib/sender.js#L222
[1]: https://github.com/zone-eu/zone-mta/blob/master/lib/sender.js#L166

**Comment by andris9** [comment]
it's been a while so you might not have this problem anymore. The response is sent by the receiving server and it seems to be 5 minutes, not 5 seconds.

10 sec timeout does not prevent message delivery. In that case zone-mta queue does not wait until the message is processed but leaves the sending process hanging and starts processing the next message. So it seems that zone-mta connects to the receiving server, something stalls for whatever reason, nothing happens and the receiving server closes the connection after 5 minutes. Complete SMTP transaction log would be needed to see what is exactly going on there.

**Comment by dazoot** [comment]
Close here too ?
