### ISSUE TITLE
What is the optimal configuration for 100K html email with 1MB attachment  per hour ?

### ISSUE THREAD

**Issue by ghost** [zone-eu/zone-mta#163]
What is the best setup, assuming sending SMTP server is clustered and can handle the required sending capacity ?

**Comment by dazoot** [comment]
I think you can fit easily on a single machine:
- 32 / 64 GB RAM
- min 250 GB SSD (raid 1)
- Xeon CPU

You can increase the number of processes per zone to squeeze more out of your machine.

I think we can close this.
