### ISSUE TITLE
Using Haproxy in front of zone

### ISSUE THREAD

**Issue by ugorey** [zone-eu/zone-mta#167]
Hi, i'm trying to use haproxy as a loadbalancer in front of zone-mta.

If i enable the the proxy protocol in haproxy i get a 421 error, if i disable the proxy protocol everything work like magic but i cannot grab the client informations like the ip.

Someone know if there is a way to manage the proxy protocol ?

Thank you

**Comment by waszi** [comment]
It should work with useProxy option in interface configuration. Unfortunately option is ignored.

**Comment by rhclayto** [comment]
@waszi I tried patching zone-mta with your fix, set useProxy=true, restarted zone-mta, set haproxy to send-proxy, & tested the connection, but it doesn't work. Hmm, this seems to be a problem. Can any of the maintainers take a look at this?

**Comment by andris9** [comment]
Published zone-mta@1.14.0 that should fix the broken PROXY support

**Comment by rhclayto** [comment]
Thanks for the quick fix!
