### ISSUE TITLE
Request for a "sender:delivered" hook

### ISSUE THREAD

**Issue by ugorey** [zone-eu/zone-mta#168]
Hi,

maybe i'm missing something but i don't find a hook to catch the "delivered" status of the email.

I managed to put a workaround in my testing env adding in lib/sender.js a custom hook but i think that a hook like this could be handy for many users.

If possibile could you add a sender:delivered hook right after the email is delievered to the next hop.

Thank you.

PS: 
my programming skills are low so i don't know if i did it correctly, i added

plugins.handler.runHooks('sender:delivered', [delivery, connection, err], () => false);

on row 519 of lib/sender.js

in my tests seem to work correctly.

Thank you.

**Comment by dazoot** [comment]
Would be nice to get also SMTP delivery message TEXT.
