### ISSUE TITLE
Single server vs multiple smaller servers

### ISSUE THREAD

**Issue by ghost** [zone-eu/zone-mta#169]
Hi guys, just discovered zone-mta on the postal forum/issues.
I'm playing around with zone right now and as I was running the installation, seeing that it uses 3 separated components, I was wondering what are your exeriences and recomendations about running everything in a bigger VPS vs 3 smaller ones and what would be the recommended hardware specs for the VMs for running all in one vs 3 independent redis + mongoDB + Node.js servers

**Comment by dazoot** [comment]
When Mongo is involved, go for dedicated. Min 8GB RAM. SSD.

**Comment by YosuCadilla** [comment]
Thank you @dazoot! I just rented a dedi to play with.

**Comment by dazoot** [comment]
This one too pls :)
