### ISSUE TITLE
gyp ERR! stack Error: `gyp` failed with exit code: 1  -   SOLVED

### ISSUE THREAD

**Issue by ghost** [zone-eu/zone-mta#170]
Hi, I'm getting this error when installing on Ubuntu 18.04
Seems python needs "-dev" version. Solved running:
# sudo apt-get install -y python-dev

root@mail ~/zone-mta-template # npm install --production

> dtrace-provider@0.8.7 install /root/zone-mta-template/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named compiler.ast
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/zone-mta-template/node_modules/dtrace-provider
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
added 201 packages from 269 contributors and audited 367 packages in 8.919s
found 0 vulnerabilities

**Comment by dazoot** [comment]
Can you close this issue ?
Not related to zonemta.
