### ISSUE TITLE
zonemta connecting remotely

### ISSUE THREAD

**Issue by ajmalkhanjamro** [zone-eu/zone-mta#173]
hello iam try to connect to zonemta from remotely iam noob so please guide how to go about that because its default install only allows localhost emails

**Comment by YosuCadilla** [comment]
@ajmalkhanjamro, please check the new extended instructions (merge might be pending)

**Comment by ajmalkhanjamro** [comment]
thanks for you reply guys i fixed the issues and its working now remotely

**Comment by dazoot** [comment]
Close the issue.
