### ISSUE TITLE
Need some light on how automatic blacklist mechanism works

### ISSUE THREAD

**Issue by nighoa** [zone-eu/zone-mta#176]
Hi zonemta community,

I'm playing since some days with this fantastic piece of software, and it's really amazing. 
Thanks for sharing that with the community.

I'm just confused with the Blacklist mecanism and I don't understand something, if someone can help me to understand.

I have setup 4 local IP to my dedicated ZoneMTA server, each one is assigned to a specific POOL like that : 

POOL 1 : IP1 1.2.3.4
POOL 2 : IP2 & IP3 1.2.3.5 & 1.2.3.6
POOL 3 : IP4 1.2.3.7

I'm sending a lot of sample e-mails to my personnal mailboxes. 
The purpose is testing the blacklist mechanism and check if zonemta is doing the job right.

With some patience (not too much) I'm getting "banned IP" error like this on a specific "outlook domain" (called domainimpacted.com) for each IPs (.4 / .5 / .6 / and .7):

> Connection closed response="550 5.7.606 Access denied, banned sending IP [1.2.3.4]. To request removal from this list please visit https://sender.office.com/ and follow the directions. For more information please go to  http://go.microsoft.com/fwlink/?LinkID=526655 (AS16012609) [HE1EUR01FT018.eop-EUR01.prod.protection.outlook.com]

I have added Prometheus and Redis metrics exporter to display everything into Grafana. 
The blacklist counter never increases on any IPs.

I have added some debug console.log, and I'm seeing that the defer counter is increased to 5 at max. But I don't see any blacklist action on the IPs impacted as banned by the remote MTA 'outlook'.

Am I doing something wrong in my test ? 

If I remove the responseData.category condition in "/opt/zone-mta/node_modules/zone-mta/lib/sending-zone.js" everything is working as "expected", I'm seeing the blacklist counter increasing for the remote domain impacted by the banned report.

```
//if (responseData.category === 'blacklist' && responseData.address && delivery.domain) {
       if (responseData.address && delivery.domain) {
```

If I dump the redis key, I see these entries : 

blacklist:domainimpacted.com:1.2.3.4
blacklist:domainimpacted.com:1.2.3.5
blacklist:domainimpacted.com:1.2.3.6
blacklist:domainimpacted.com:1.2.3.7

So the blacklist mecanism is working well, it's just a "problem" with the condition. 

From my understanding, the responseData.category is egal to "defer", and never change to "blacklist" even if it reach a max count of 5.

What is the logical used to manage a message from the defer category to a blacklist category ?
 
Is it normal if the remote MTA "outlook" is saying that the sending IP 1.2.3.4 is banned from their side ?

If you can give me some light, help is welcome ;)

Nighoa

**Comment by andris9** [comment]
Bounce messages are parsed using regexes and matched against known patterns to detect blacklisting. The bounce message you provided was detected invalidly due to a typo in the compare pattern.

please upgrade zone-mta to v1.15.4 to fix this

**Comment by nighoa** [comment]
Thanks a lot @andris9 you are the Man !🥇
