### ISSUE TITLE
1.15.5 does not start

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#178]
After upgrading to 1.15.5 the server does not start anymore.

```
Mar 21 11:35:36 tlhp1 zone-mta: /usr/local/zonemta/node_modules/csv-parse/lib/index.js:19
Mar 21 11:35:36 tlhp1 zone-mta:     super({...{readableObjectMode: true}, ...opts})
Mar 21 11:35:36 tlhp1 zone-mta:            ^^^
Mar 21 11:35:36 tlhp1 zone-mta:
Mar 21 11:35:36 tlhp1 zone-mta: SyntaxError: Unexpected token ...
Mar 21 11:35:36 tlhp1 zone-mta:     at createScript (vm.js:56:10)
Mar 21 11:35:36 tlhp1 zone-mta:     at Object.runInThisContext (vm.js:97:10)
Mar 21 11:35:36 tlhp1 zone-mta:     at Module._compile (module.js:549:28)
Mar 21 11:35:36 tlhp1 zone-mta:     at Object.Module._extensions..js (module.js:586:10)
Mar 21 11:35:36 tlhp1 zone-mta:     at Module.load (module.js:494:32)
Mar 21 11:35:36 tlhp1 zone-mta:     at tryModuleLoad (module.js:453:12)
Mar 21 11:35:36 tlhp1 zone-mta:     at Function.Module._load (module.js:445:3)
Mar 21 11:35:36 tlhp1 zone-mta:     at Module.require (module.js:504:17)
Mar 21 11:35:36 tlhp1 zone-mta:     at require (internal/module.js:20:19)
Mar 21 11:35:36 tlhp1 zone-mta:     at Object.<anonymous> 
(/usr/local/zonemta/node_modules/csv/lib/index.js:6:10)
```

Node version:
v6.15.0

**Comment by andris9** [comment]
It seems that Restify (one of the dependencies of ZoneMTA) requires a newer version of Node.

**Comment by dazoot** [comment]
So maybe we should upgrade the requirements in the README file.

**Comment by andris9** [comment]
Yeah, good point. I've tried to not use anything myself that would break compatibility with Node 6 but I use v10 everywhere and if dependencies break because of that then I might not notice. Downgrading Restify would probably also be an option.

**Comment by dazoot** [comment]
I think this is the best for now:
- downgrade restify
- make a planned requirements upgrade to higher Node version so ppl have time to upgrade (like in the next 3 months)

Is this ok ?

**Comment by dazoot** [comment]
Faster is to just update the Readme with requirements and move on :)

**Comment by andris9** [comment]
I downgraded Restify to v7.7.0 so it should work with Node v6 again. I don't plan to drop support for Node 6 any time soon, but eventually it will happen though, once I can't go with older dependencies anymore.
