### ISSUE TITLE
Zone-MTA and loosing connection with a MX

### ISSUE THREAD

**Issue by nighoa** [zone-eu/zone-mta#182]
Hi !

I just able to reproduce a strange behaviour. 

Suppose that you have just a lot of emails to send to mailboxes for a dedicated company "example.com".

You have selfhosted a Wildduck MX server with a lot of mailboxes : user1@example.com, user2@example.com, etc.

You send a lot of emails to theses users with Zone-MTA.

Everything is working properly, and at a time, you decide to stop the Wildduck (haraka stop) MX server of the example.com company.

ZoneMTA will concider every connections to this MX server as : a Network error / connection refused.

`info Sender/acquisition/12223[1] 169d965c5700001b3e.001 DEFERRED[recipient] from=bounce@example.com to=xrdtykdqxk@example.com src= mx=example.com id=<0ced4de5-ddb6-d031-54c5-51e92dff71ba@example.com> (450 Network error when connecting to MX server mail.example.com[1.1.1.1] for example.com: Connection refused)`

This is "normal" because we shutdown the MX server... but what is strange it's when you start again the MX server (haraka start). 

ZoneMTA don't check the new connection state of the MX server and keep the status of "450 Network error". Every emails in the deliver queue are slowly processed and migrated to the "DEFFERED queue".

If you just restart the whole Zone-MTA service, all the emails are sent correctly to the MX server example.com instantly.

I suspect a "cache" about the connection state from a remote MX.

Are you aware of it ?

**Comment by andris9** [comment]
Yes, there is a 10 minute cache for failing network connections. This is to prevent accumulating large amount of connections to a server that does not accept any. Normally if it's false positive then all the deferred messages should get resolved in 10 minutes or so.
