### ISSUE TITLE
Plugins run order

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#190]
Is there a way to specify plugins run order ?
For example if there are more `message:headers` plugins, i would like some to run before others.

**Comment by andris9** [comment]
Plugins are run in the same order they are defined

**Comment by dazoot** [comment]
If you have:
```
[plugins]
# @include "plugins/*.toml"
```

the order is not that clear.

But yes, you can list them all and they run in order.
All good.

**Comment by andris9** [comment]
Oh yeah,  in this case you can order plugins by filenames. Use numeric prefix.

```
00-plugin-1.toml
00-plugin-2.toml
...
```
