### ISSUE TITLE
Attachment deduplication for zonemta

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#191]
Wild duck imap server has attachment deduplication. 
Would be nice to have this feature in Zonemta as well.

**Comment by andris9** [comment]
Do you have a specific use case in mind? Difference between WD and Zmta is that WD storage is long lived and permanent. Zmta storage (message queue) is temporary. So even if you get a temporary gain (large batch of messages with the same attachment are queued), you loose the gain pretty fast once the messages are delivered.

**Comment by dazoot** [comment]
We had a bulk issue today when a user sent ~10k mails with 5MB attachment each. Our mongodb almost died. If we had attachment deduplication the write would be just ~5MB not 5GB (all in a short period of time).

**Comment by dazoot** [comment]
Not really needed for outgoing purpose only.
