### ISSUE TITLE
Ipv6 errors for default mode

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#193]
I did not enable ipv6 on my setup but i see ipv6 attempts. 

ERR! Sender/allip_tlhp1/30859[4] 16b919bc782000e6e1.001 CONNFAIL domain=powerview.it local=tlhp1.com[::] remote=2001:4b78:1001::70b:25 error=Network error when connecting to MX server m-07b.th.seeweb.it[2001:4b78:1001::70b] for powerview.it: Network is unreachable

**Comment by andris9** [comment]
This server does not have IPv4, only IPv6 so ZoneMTA seems to fall back to using IPv6.

Do you have set `ignoreIPv6:true` in your zone options? This should disable IPv6 checks.

**Comment by dazoot** [comment]
I have ignoreIpv6 = true. 
Is it case sensitive ?

**Comment by andris9** [comment]
Yes, all options are case sensitive

IPv6 related settings are:
* `preferIPv6` - if `true` then tries AAAA first and falls back to A if not found. If `false` then checks A first and falls back to AAAA if not found.
* `ignoreIPv6` - if `true` then does not check AAAA record even if A is not found.
