### ISSUE TITLE
It is posible to send emails behind haproxy?

### ISSUE THREAD

**Issue by Weldeasy** [zone-eu/zone-mta#194]
Hello there!

I've setup zone-mta behind haproxy, but when it tries to connect the MX of the recipients says:

Jul 11 19:03:39 mta zone-mta[12466]: info Sender/default/12496[4] 16be1fd83d4000eaca.002 DEFERRED[recipient] from=oscar@my.mail to=oscar@their.mail src= mx=their.mail id=<e4b5dee9-9c8d-adc0-491f-23e3c66d432d@my.mail> (450 Network error when connecting to MX server mail.their.mail[1.2.3.4] for their.mail: Connection timed out)

What is wrong?

**Comment by jadsolucions** [comment]
I'm facing the same problem!

**Comment by dazoot** [comment]
Seems you have firewall or connection issues. Haproxy is for incoming.

**Comment by Weldeasy** [comment]
Yup! Solved. Thank you.
