### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by soncodi** [zone-eu/zone-mta#2]
Would you be interested in converting this project to TypeScript?

**Comment by andris9** [comment]
No, not really, I think that the code should be as vanilla JS as possible. It seems to me that transpiling code makes it harder to debug edge cases where a long running daemon starts to act crazy. It's easier to look at hand-written code to find the culprit in this case.

**Comment by soncodi** [comment]
An argument in favor is reduced need to pass around bags of magic/data, generating fewer TypeErrors at runtime. This is great if more devs join the project - the code becomes self-documenting. Now that you've added a plugin system, this is even more important, imo. Benefits are more apparent as the codebase grows (refactoring, etc).

The transition is lightweight: rename *.js => *.ts and add a build step. If you change your mind, I can setup an example fork to try out.
