### ISSUE TITLE
Question about installing ZoneMTA

### ISSUE THREAD

**Issue by brinnington** [zone-eu/zone-mta#202]
![zonemta_start](https://user-images.githubusercontent.com/45102823/65971997-0c401e00-e461-11e9-856a-0d5aa9763324.png)

Hi,

I have a question about the installation of Zone-MTA. The steps that I was using are:
$ git clone git://github.com/zone-eu/zone-mta-template.git
$ cd zone-mta-template
$ npm install eslint --save-dev
$ npm init
$ npm install --production
$ npm start

The last step, npm start, looks to me as though it hung, because it ends with "info Redis/4412 Redis ready to take connections" and doesn't return to the prompt. Please see the attached png file.

Please clarify for me whether it has hung or whether it is supposed to end like that. And if it is supposed to end like that, how do I return to the prompt?

Thank you.

Best,

Bob

**Comment by andris9** [comment]
The app is working

**Comment by andris9** [comment]
There is no prompt. It’s a server daemon. You can connect to it using SMTP port 2525

**Comment by brinnington** [comment]
Hi andris9, Thanks very much for clarifying that for me.

Best,

Bob

**Comment by brinnington** [comment]
Hi andris9, 

How do I get back to the prompt? I want to install amta-webadmin.

Best,

Bob

**Comment by louis-lau** [comment]
By running `npm start`. If you want it to keep running in the background when you close the terminal you can run it as a systemd service. A .service file is included in the repo.

**Comment by brinnington** [comment]
Hi Louis-Lau,

Thank you for the info. I have found the script for the systemd service (https://github.com/zone-eu/zone-mta/blob/master/setup/zone-mta.service). However, as I am not familiar with systemd and ZoneMTA, please tell me the location of the file that the script goes in.

Thank  you.

Best,

Bob
)

**Comment by louis-lau** [comment]
Instead of blindly following instructions you might want to get familiar with a technology if you're going to use it 😁.

Got these from a quick Google.
https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
https://www.linode.com/docs/quick-answers/linux/start-service-at-boot/

**Comment by brinnington** [comment]
Hi Louis-Lau,

But I don't want to learn the technology. I want to use ZoneMTA.

Thanks for the links.

Best,

Bob
