### ISSUE TITLE
nginx server block

### ISSUE THREAD

**Issue by brinnington** [zone-eu/zone-mta#203]
Hi,

I have installed Zone-MTA on a server with nginx.

Normally I would create a server block on nginx for a website such as WordPress.

I have two questions:

(i) Will I have to create a server block for Zone-MTA?

(ii) If I have to create a server block for Zone-MTA, is there an example of such a server block? I have looked at the documentation that came with Zone-MTA and the Wiki but I could not find any examples.

Thanks your help on this.

Best,

Bob

**Comment by dazoot** [comment]
You can use nginx xclient with zonemta. 

You can set in your smtpInterfaces: `useXClient = true` and configure your nginx to sit in front of zonemta (mailproxy). Some examples here: https://www.nginx.com/resources/wiki/community/faq/#mail-proxying

Anyway, this is not the place to ask questions like this.
This is not a bug / issue.
