### ISSUE TITLE
Can a plugin deferr a message ?

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#204]
Can a plugin deferr a message ?
For example to schedule the send retry for later insted of attempting to deliver now.
Any example ?

**Comment by andris9** [comment]
You could defer a message by returning an error with a 4xx status code. This counts against defer max counter so if you defer the same message too many times it will be dropped

**Comment by dazoot** [comment]
If i return an error in `sender:connect` the mail gets REJECTED not DEFERRED.

**Comment by dazoot** [comment]
Works if i add action = defer.
```
err.responseCode = 421;
err.action = "defer";
```
