### ISSUE TITLE
Retry interval

### ISSUE THREAD

**Issue by echodreamz** [zone-eu/zone-mta#212]
How often are messages retried after being deferred? I cannot seem to find any settings that state how often to retry greylisted / deferred messages.

Thanks!

**Comment by louis-lau** [comment]
See here :)
https://github.com/zone-eu/zone-mta/blob/5c9a427580821c835091261af401c8e1f3d7d6a4/lib/sender.js#L26-L44

**Comment by echodreamz** [comment]
Thanks!
