### ISSUE TITLE
mongo ssl=true connect issues after upgrade to 1.7.1

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#217]
I did an upgrade to 1.7.1 and on startup i get an error that server selection timed out.

```
mongo="mongodb://host1:27017,host2:27017/zone-mta?replicaSet=Mail&ssl=true"
```

If i remove the `ssl=true` flag, zonemta starts ok.

**Comment by dazoot** [comment]
Can we downgrade the mongo package to fix this ?

**Comment by andris9** [comment]
Try to use `tls=true` instead of `ssl=true`

**Comment by dazoot** [comment]
Same error:
```
Queue Could not initialize database: Server selection timed out after 30000 ms
```

**Comment by andris9** [comment]
Ok, I'm not sure about the exact config in this case. Mongodb module can not be downgraded as it is a critical dependency. I think the newer mongodb version is using a bit different formatted connection string, you should probably check out official mongo docs how to format it.

Btw if zonemta starts fine without `ssl=true` then are you sure your server is even using TLS?

**Comment by dazoot** [comment]
My mongod (3.6) is set to use SSL:
```
  ssl:
    mode: preferSSL
```

If i add `tlsInsecure=true` to the connection string it works. 
We close this as it seems it's cert issue.
