### ISSUE TITLE
1.17.0 TypeError

### ISSUE THREAD

**Issue by echodreamz** [zone-eu/zone-mta#221]
`Jan 21 23:20:03 zone-mta node: /opt/zone-mta/node_modules/mailsplit/lib/headers.js:145
Jan 21 23:20:03 zone-mta node: let headers = this.lines.map(line => line.line.replace(/\r?\n/g, lineEnd)).join(lineEnd) + ${lineEnd}${lineEnd};
Jan 21 23:20:03 zone-mta node: ^
Jan 21 23:20:03 zone-mta node: TypeError: line.line.replace is not a function
Jan 21 23:20:03 zone-mta node: at headers.lines.map.line (/opt/zone-mta/node_modules/mailsplit/lib/headers.js:145:56)
Jan 21 23:20:03 zone-mta node: at Array.map (<anonymous>)
Jan 21 23:20:03 zone-mta node: at Headers.build (/opt/zone-mta/node_modules/mailsplit/lib/headers.js:145:34)
Jan 21 23:20:03 zone-mta node: at plugins.handler.runHooks.err (/opt/zone-mta/node_modules/zone-mta/lib/sender.js:257:67)
Jan 21 23:20:03 zone-mta node: at Immediate.checkNext (/opt/zone-mta/node_modules/zone-mta/lib/plugin-handler.js:429:24)
Jan 21 23:20:03 zone-mta node: at runCallback (timers.js:705:18)
Jan 21 23:20:03 zone-mta node: at tryOnImmediate (timers.js:676:5)
Jan 21 23:20:03 zone-mta node: at processImmediate (timers.js:658:5)
Jan 21 23:20:03 zone-mta node: ERR! Child/default/15909 [3428ef5eb670ba495bda] Sender process for default exited with 1
Jan 21 23:20:03 zone-mta node: info Child/default/16288 [9e4c8c69a994fd3babdf] Spawning sender process for default
Jan 21 23:20:03 zone-mta node: /opt/zone-mta/node_modules/mailsplit/lib/headers.js:145
Jan 21 23:20:03 zone-mta node: let headers = this.lines.map(line => line.line.replace(/\r?\n/g, lineEnd)).join(lineEnd) + ${lineEnd}${lineEnd};
Jan 21 23:20:03 zone-mta node: ^
Jan 21 23:20:03 zone-mta node: TypeError: line.line.replace is not a function
Jan 21 23:20:03 zone-mta node: at headers.lines.map.line (/opt/zone-mta/node_modules/mailsplit/lib/headers.js:145:56)
Jan 21 23:20:03 zone-mta node: at Array.map (<anonymous>)
Jan 21 23:20:03 zone-mta node: at Headers.build (/opt/zone-mta/node_modules/mailsplit/lib/headers.js:145:34)
Jan 21 23:20:03 zone-mta node: at plugins.handler.runHooks.err (/opt/zone-mta/node_modules/zone-mta/lib/sender.js:257:67)
Jan 21 23:20:03 zone-mta node: at Immediate.checkNext (/opt/zone-mta/node_modules/zone-mta/lib/plugin-handler.js:429:24)
Jan 21 23:20:03 zone-mta node: at runCallback (timers.js:705:18)
Jan 21 23:20:03 zone-mta node: at tryOnImmediate (timers.js:676:5)
Jan 21 23:20:03 zone-mta node: at processImmediate (timers.js:658:5)
Jan 21 23:20:03 zone-mta node: ERR! Child/default/15861 [3c40daf9843460f5183f] Sender process for default exited with 1
`

Tried a fresh installation as well, the error persists. Going back to a backup of 1.16.4 fixes this issue.

**Comment by jpbede** [comment]
Do you use version 1.7.1 ? If not, please do so. There was a fix.

**Comment by echodreamz** [comment]
Should the zone-mta-template repo be updated for the package.json? It still points to 1.17.0.

**Comment by jpbede** [comment]
Indeed. I've created a PR with a fix for that.
