### ISSUE TITLE
unable to insall zone mta

### ISSUE THREAD

**Issue by bpareek9694** [zone-eu/zone-mta#223]
Hello all,

I'm unable to install zone-mta in my server.
i'm using this [doc](https://github.com/zone-eu/zone-mta-template)

In this doc, we're unable to executive all command,
Please check below code and error,
`# npm start`
`info App  ---------------------------------------------------------------
info App
info App  ███████╗ ██████╗ ███╗   ██╗███████╗███╗   ███╗████████╗ █████╗
info App  ╚══███╔╝██╔═══██╗████╗  ██║██╔════╝████╗ ████║╚══██╔══╝██╔══██╗
info App    ███╔╝ ██║   ██║██╔██╗ ██║█████╗  ██╔████╔██║   ██║   ███████║
info App   ███╔╝  ██║   ██║██║╚██╗██║██╔══╝  ██║╚██╔╝██║   ██║   ██╔══██║
info App  ███████╗╚██████╔╝██║ ╚████║███████╗██║ ╚═╝ ██║   ██║   ██║  ██║
info App  ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝     ╚═╝   ╚═╝   ╚═╝  ╚═╝
info App
info App  ----------------------- zone-mta@1.17.1 -----------------------
info App
info SMTP/feeder SMTP feeder MTA server started listening on port 2525
info QS Queue server started
info API API server started
ERR! Redis/32760 connect ECONNREFUSED 127.0.0.1:6379
ERR! Queue Could not initialize database: connect ECONNREFUSED 127.0.0.1:6379

npm ERR! Linux 4.4.0-173-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zone-mta-template@1.5.0 start: `node index.js --config=config/zonemta.toml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zone-mta-template@1.5.0 start script 'node index.js --config=config/zonemta.toml'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zone-mta-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js --config=config/zonemta.toml
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zone-mta-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zone-mta-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2020-02-10T10_37_17_379Z-debug.log`

Please help me to install zone-mta

**Comment by jpbede** [comment]
Hey,

is the Redis Server running ? 
The log says it can't connect to redis.

**Comment by bpareek9694** [comment]
@jpbede Thanks for the reply,

i install in Ubuntu 16.04 in fresh server,

Please guide me, how can i install zonemta i fresh ubuntu server

**Comment by louis-lau** [comment]
People can't help you if you don't answer their questions. So, have you installed redis and is it running?

**Comment by bpareek9694** [comment]
please check the below output of redis server
![image](https://user-images.githubusercontent.com/53152540/74143790-780d7100-4c21-11ea-9790-59cf1c92e0f1.png)

Please help me.

**Comment by louis-lau** [comment]
Then you haven't installed it. It is clearly listed under the requirements of ZoneMTA. Please install redis first.

**Comment by bpareek9694** [comment]
@louis-lau Thanks For Replay,

I reinstall the server,

And configure all requirement
1. Node.js in this [doc](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04)
2. MongoDB in this [Doc](https://www.linuxhelp.com/how-to-install-mongodb-on-ubuntu-16-04)
3. Radis on this [Doc](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04)
And radis service is **active**.
![image](https://user-images.githubusercontent.com/53152540/74149702-6088b500-4c2e-11ea-9570-7b71692a2ef9.png)



After that i can install this :-
![image](https://user-images.githubusercontent.com/53152540/74149501-e22c1300-4c2d-11ea-8afb-f31d803e52d7.png)

but when executive last cmd is hanged
![image](https://user-images.githubusercontent.com/53152540/74149563-0be53a00-4c2e-11ea-9bba-942aabe2ebaf.png)

Please guide me how can i install zonemta in fresh ubuntu server

**Comment by jpbede** [comment]
No, it is not hanging ... It is running ...

**Comment by bpareek9694** [comment]
Thanks for replay,

I'm waiting for 2 hours,
but it still remain same.

![image](https://user-images.githubusercontent.com/53152540/74166176-24fce380-4c4c-11ea-93e2-b16f879084b6.png)

Can you advice me what i'm doing wrong?

**Comment by louis-lau** [comment]
You're not. This is it. It's working. You can use it. Waiting won't do anything.

**Comment by jpbede** [comment]
Again, it is running ... What do you expecting it should do ?!

**Comment by bpareek9694** [comment]
@louis-lau & @jpbede 
Thanks for replay

@jpbede I'm just expecting that the processes will take not more than an hour.

Can you please tell me how much time the process will take?

**Comment by louis-lau** [comment]
What process? It is already done. Read our replies again.

**Comment by jpbede** [comment]
It is running in foreground. It is waiting for your connections ...

**Comment by bpareek9694** [comment]
Ok Thanks.....for Your Quick Support
