### ISSUE TITLE
Add Dkim in Zone-mta

### ISSUE THREAD

**Issue by bpareek9694** [zone-eu/zone-mta#224]
Hi all,

How can add dkim (dns records) in zone mta server ?

**Comment by jpbede** [comment]
Please read the docs carefully 

https://github.com/zone-eu/zone-mta/blob/master/README.md#dkim-signing

**Comment by jpbede** [comment]
Or check this https://github.com/zone-eu/zone-mta-template/blob/master/config/plugins/dkim.toml

**Comment by bpareek9694** [comment]
@jpbede Thanks for help
