### ISSUE TITLE
Add multiple user and credential

### ISSUE THREAD

**Issue by bpareek9694** [zone-eu/zone-mta#225]
Hello all,

how to add multiple users and credentials in the zone-mta ?

Please suggest to me.

**Comment by jpbede** [comment]
Once again, read the docs and the code ... Use a plugin or do a call against a API

https://github.com/zone-eu/zone-mta/blob/master/config/default.js#L70
https://github.com/zone-eu/zone-mta-template/blob/master/plugins/example-auth.js

**Comment by andris9** [comment]
ZoneMTA is more like a building block or framework, not a complete MTA like, for example, Postfix. ZoneMTA can handle SMTP but all integrations with other systems (eg authentication) are custom made.
