### ISSUE TITLE
Forcing next hop based on X-header

### ISSUE THREAD

**Issue by DeadlyBug** [zone-eu/zone-mta#232]
Hello,

I am managing a setup where multiple outgoing SMTP servers are connected to the internet.
The need is to introduce non random load balancing over these servers by using a X-Header in each email which is used force the next hop, bypassing traditionnal mx resolution.
This seems to be achievable by  having a Zone-MTA relay in front of the cluster of SMTP and using the sender:connect feature to provide a socket object as discussed on https://github.com/zone-eu/zone-mta/tree/master/plugins: "_'sender:connect' with arguments delivery, options called before connection is tried to open against the MX. If the options object includes a property socket after hook is finished, then this socket object is used to start the SMTP session_"

Is this the best approach to achieve such a goal? It seems like Sending Zones are more relevant when the Zone-MTA server itself has multiple IP aliases, which is not the case here.

Documentation on the topic is scarce so any help is appreciated: the only reference to use of the sender:connect context is an issue with the use of this directive along with custom DKIM management on https://github.com/zone-eu/zone-mta/issues/143

**Comment by louis-lau** [comment]
If I understand your usecase correctly then ZoneMTA can actually do this natively! For each of your existing relays, create a sending zone. Then configure that sending zone to deliver emails to your relay. See the example config: 
https://github.com/zone-eu/zone-mta/blob/2557a975ee35ed86e4d95d6cfe78d1b249dec1a0/config/default.js#L389

Then you can have ZoneMTA use specific zones for specific headers as described in the readme :)

**Comment by DeadlyBug** [comment]
Hello
Thanks for your feedback, I will try that.
