### ISSUE TITLE
[rspamd/clamav] How to scan messages that are directly pushed to queue?

### ISSUE THREAD

**Issue by v-byte-cpu** [zone-eu/zone-mta#237]
Is it possible to scan messages that are pushed directly to mongodb collection using rspamd/clamav plugins for ZoneMTA ?

Right now scan is performed only if message sent via ZoneMTA SMTP interface (MSA). To clarify things, I use Wildduck + ZoneMTA + (zonemta-wildduck plugin). I want to scan messages that are sent via Wildduck webmail. Maybe wildduck should use ZoneMTA API instead of directly pushing to mongodb collection.

**Comment by andris9** [comment]
Currently there is no ay to scan messages from webmail. This is a planned feature, probably as an option for the message upload API call. No ETA at this point though

**Comment by v-byte-cpu** [comment]
@andris9 ok, thank you. I will wait it

**Comment by dazoot** [comment]
Can we close this cause it's a Wildduck feature request not ZoneMTA related.

**Comment by v-byte-cpu** [comment]
@andris9 Is this issue tracked anywhere ?
