### ISSUE TITLE
Is it possible to have plugins per zone?

### ISSUE THREAD

**Issue by kesavkolla** [zone-eu/zone-mta#238]
I want to bypass some plugins when I'm sending via particual zone.  I've a scenario where I want to bypass the wildduck plugin which does from address re-write only when I'm using certain zone.  Is it possible to achieve this?

**Comment by andris9** [comment]
At this point no, WildDuck more or less takes everything over once enabled. The easiest route would be to install a separate ZoneMTA instance for non-wildduck messages.
