### ISSUE TITLE
connection reuse dkim sign issue

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#240]
Our DKIM sign plugin uses `sender:connect` hook as suggested in the documentation.

In connection reuse mode (eg: more mails are sent on the same connections) the hook is called only for the first message thus subsequent mails do not get DKIM.

Seems like a major bug.

**Comment by dazoot** [comment]
@jpbede can you confirm this ?

**Comment by jpbede** [comment]
Yep, that's indeed right. Let me check this and create a fix

**Comment by jpbede** [comment]
The question is now: Should we use a new hook, like `sender:reuse` or like this, or should we call the existing `sender:connect` hook.

I would prefer a new hook. What do you think @dazoot @andris9 ?

**Comment by dazoot** [comment]
+1 for new hook.

**Comment by dazoot** [comment]
The thing is that this hook should be called always not just for `reuse`. Also for `firstuse`. Also for situations when users disable connection reuse.

**Comment by dazoot** [comment]
Maybe make a hook for dkim ?
`sender:dkim`

**Comment by jpbede** [comment]
Okay, that would explain the issues we had. PR is ready, see [PR241](https://github.com/zone-eu/zone-mta/pull/241). The hooks is now called before a connection is established or reused.

**Comment by jpbede** [comment]
We use `sender:fetch` for that.

**Comment by andris9** [comment]
The new hook to process dkim signatures is 'sender:connection'. Previous 'sender:connect' wasn't great anyway because it might get triggered multiple times per one email (if the first MX does not respond, then second MX is attempted and for each MX attempt 'sender:connect' was called)

```
app.addHook('sender:connection', (delivery, connection, next) => {
   next();
});
```

**Comment by dazoot** [comment]
In my plugin i get an error now:
```
return next();

 TypeError: next is not a function
```

What changed ?

**Comment by dazoot** [comment]
Seems i have to do:
`app.addHook('sender:connection', (delivery, options, next) => {`

**Comment by louis-lau** [comment]
You always have to get `next` as an argument, nothing changed about that 😁

**Comment by dazoot** [comment]
I was using @jpbede hook `sender:connecting` which was not sending `options` parameter. 
All clear now.

**Comment by andris9** [comment]
It is not `options` but `connection`. If you do not use it, then it does not matter what name you use though.
