### ISSUE TITLE
Rewrite content message

### ISSUE THREAD

**Issue by protuanna** [zone-eu/zone-mta#242]
Hi All, 
I want rewrite mail content to tracking . I want to ask which hook can I use
Thanks

**Comment by protuanna** [comment]
@andris9 Can you help me, please

**Comment by andris9** [comment]
It seems like a bug on ZoneMTA itself. I'm currently working on other issues so I'm not sure when will I be able to dig deeper and fix it.

**Comment by andris9** [comment]
You would have to use [message rewriter](https://github.com/zone-eu/zone-mta/tree/master/plugins#using-message-rewriter). It is not easy to use as you'd have to process MIME nodes separately. Here's an [example](https://github.com/andris9/mailsplit/blob/master/examples/rewrite-html.js) for editing HTML

**Comment by protuanna** [comment]
many thanks @andris9
