### ISSUE TITLE
Set SendingZone by routingHeaders not work

### ISSUE THREAD

**Issue by protuanna** [zone-eu/zone-mta#243]
Hi all 
I set zone but not work :( 
<img width="1186" alt="Screen Shot 2020-07-15 at 10 30 50 AM" src="https://user-images.githubusercontent.com/12640433/87500404-86573180-c686-11ea-88ca-062191c3a26c.png">

<img width="1395" alt="Screen Shot 2020-07-15 at 10 31 10 AM" src="https://user-images.githubusercontent.com/12640433/87500426-92db8a00-c686-11ea-9975-3fce03e9fa16.png">

and 
`if (!delivery.updates) {
            delivery.updates = {};
        }
        delivery.updates.sendingZone = 'thuocquynuocnam';`

**Comment by andris9** [comment]
This seems to be a bug in the routing headers initialisation. These are loaded into a wrong process.

**Comment by protuanna** [comment]
> This seems to be a bug in the routing headers initialisation. These are loaded into a wrong process.

This is client bug or zone mta ? .

**Comment by protuanna** [comment]
i fixed it . Many thanks :D

**Comment by Luskan777** [comment]
Hi @protuanna ,

How did you fix this?

**Comment by vivekpatel5996** [comment]
Hi @protuanna, How you fixed that ?

Hi @protuanna , Did you find any solution for that ?

Thanks
