### ISSUE TITLE
Bounces naming convention should stick to "category"

### ISSUE THREAD

**Issue by niftylettuce** [zone-eu/zone-mta#244]
https://github.com/zone-eu/zone-mta/blob/master/config/bounces.txt

I think it'd be better to put "category" or "categories" instead of "reasons" or "reason" for parity.

**Comment by andris9** [comment]
Fixed in https://github.com/zone-eu/zone-mta/commit/2acc562560f6e5c26a135fb2a11063d85eed9444

**Comment by dazoot** [comment]
Close ?
