### ISSUE TITLE
SSL error when sending message with SMTP

### ISSUE THREAD

**Issue by duyhotan2000** [zone-eu/zone-mta#256]
Hi ,

I have installed Wildduck on server and configured ZoneMTA with Let's encrypt certificate for SMTP TLS, but when sending email from Thunderbird, I got this error:
![image](https://user-images.githubusercontent.com/10768153/98229582-ac357880-1f8c-11eb-9ab8-fefff7772f97.png)

I also checked the syslog and got them following error:
![image](https://user-images.githubusercontent.com/10768153/98229639-bbb4c180-1f8c-11eb-86d9-19d995cde590.png)

Please give me some clues.
Thank you!

**Comment by andris9** [comment]
This usually means that server and client support different TLS ciphers. You could try to connect to your server via command line to see if connections are even possible

```
openssl s_client -connect mail.lynda.vn:587 -starttls smtp
```

**Comment by duyhotan2000** [comment]
Here is the result 
![Screen Shot 2020-11-05 at 17 54 54](https://user-images.githubusercontent.com/10768153/98232342-21567d00-1f90-11eb-9cd7-437f586b14bb.png)

**Comment by andris9** [comment]
Do you get the same error when running the command directly in your server?

```
openssl s_client -connect 127.0.0.1:587 -starttls smtp
```

**Comment by duyhotan2000** [comment]
It didn't work. Still having the error.
![Screen Shot 2020-11-05 at 18 02 44](https://user-images.githubusercontent.com/10768153/98233114-1cde9400-1f91-11eb-8524-b3d3ab8cf332.png)

**Comment by andris9** [comment]
In this case could you check if the Let's encrypt keys and cert are valid and readable for the zone-mta process?

You can see the valid configuration by using this (you might have to edit paths if you are using a different configuration):

```
$ cd /opt/zone-mta
$ NODE_CONFIG_ONLY=true /usr/bin/node index.js --config="/etc/zone-mta/zonemta.toml"
```

Look for `smtpInterfaces.feeder.cert` and `smtpInterfaces.feeder.keys` values. See if the file content seems OK. Also check file permissions for these files, eg by trying to read these with the email service user

```
sudo -u wildduck cat /etc/wildduck/certs/fullchain.pem
```

**Comment by duyhotan2000** [comment]
Thank you. They’ve permission issue and I fixed them. 
But now I still could not send mail via SMTP because of authentication error.
The username/password is same as IMAP, and IMAP works.
Do I miss any configuration?

**Comment by duyhotan2000** [comment]
Thank you!
wildduck user could not access those key files. I have fixed it and it worked well.
