### ISSUE TITLE
MTA

### ISSUE THREAD

**Issue by x4team** [zone-eu/zone-mta#257]
**Hello! Thank you for your efforts.** 

I have a problem with the server zone-mta.
When I uncomment lines SMTP gmail in config in any of the zones ~/zone-mta/config/default.js, then
zone-mta doesn't start and gives an error:

`Nov 29 19:01:48  node[7864]: [/home/ubuntu/zone-mta/config/default.js] /home/ubuntu/zone-mta/config/default.js: Unexpected identifier`

```
            bounces: {
            preferIPv6: false,
            ignoreIPv6: true,
            connections: 10,
            processes: 1,
            //zone specific logging
           // logger: true,
            //logLevel: 'silly'
            host: 'smtp.gmail.com',
            port: 587,
            auth: {
                user: 'myusername@gmail.com',
                pass: 'mypassword'
            }
            pool: 'default'
        }
```

It does not matter in which zone I want to register my smtp, immediately an error and refusal to work. :((
With what it can be connected?
Thank you!

**Comment by louis-lau** [comment]
JSON does not support comments.

**Comment by x4team** [comment]
> JSON does not support comments.

If I comment again lines with SMTP, then all works.

```
//host: 'smtp.gmail.com',
//            port: 587,
//            auth: {
//                user: 'myusername@gmail.com',
//                pass: 'mypassword'
//            }
```

**Comment by x4team** [comment]
What am I doing wrong? After all, I'll just uncomment what was already in the config by default

**Comment by louis-lau** [comment]
I guess the parser doesn't mind comments then 👍 

Can you post a complete config example that fails? I'd still recommend using the template and using TOML. It's much better suited to configuration management than JSON.

**Comment by louis-lau** [comment]
Aaand I only just noticed the default config is a javascript object, not JSON. That does support comments of course 🤦. Whoops.

**Comment by x4team** [comment]
Surprising fact, I uncommented the entire zone and removed the options I didn't need. And it worked! I have not tested it with the default zone yet. Thanks for the advice, probably some kind of glitch?
```
        bounces: {
            preferIPv6: false,
            ignoreIPv6: true,
            connections: 10,
            processes: 1,
            senderDomains: ['headway.ai'],
            host: 'smtp-relay.gmail.com',
            port: 587,
            pool: 'default'
        }
```
It is also possible that commas are not everywhere in the commented out lines. Therefore, when I uncomment,  do not notice that there are no commas

**Comment by x4team** [comment]
Yes it works! All attention to the commas. It turns out I was blind. I am sorry for disturbing you!
