### ISSUE TITLE
Zone-MTA + Mailcow

### ISSUE THREAD

**Issue by x4team** [zone-eu/zone-mta#258]
Hello!
Help with advice and, if possible, a solution.
There is a full-fledged Mailcow server, which is configured with a domainname1.com. I want to send mail on behalf of this domain through the Zone-MTA, and not through the Mailcow, that is, configure a route for mail relay to localhost: 2525.
But the Zone-MTA allows sending only from the localhost, and the MailCow server is located in docker containers, and therefore it is impossible to access the host from it. Is it possible to get around this somehow?
For example, I can access the host Zone-MTA via interface 172.24.0.1. Can the Zone-MTA be configured for work from this IP? 
Thank you!

P.S.
I'll tell you why I need to do this. Since there is a domainname2.com, which is the alias for the main domainname3.com in Google Gsuite. And I need to make an alias domainname1.com for domainname2.com, but Google prohibits making an alias for the alias. 
Therefore, I need to configure the relay of mail from the domainname1.com (Mailkow server) to the domainname2.com (Google Gsuite).
There may still be a problem here, that Google will swear, that any sender will be forged by the Zone-MTA server

**Comment by andris9** [comment]
You can define the IP address zone-mta binds to using this [config option](https://github.com/zone-eu/zone-mta-template/blob/master/config/interfaces/feeder.toml#L13) (defaults to 127.0.0.1)

**Comment by x4team** [comment]
Thanks!
For those who are interested in the implementation with docker:

1) We learn on the IP host of the docker network interface:
`ip addr show docker0`

2) Add a rule:
`sudo iptables -A INPUT -i docker0 -j ACCEPT`

3) We use IP for your purposes:
test from docker container `telnet 172.17.0.1 2525`

**Comment by dazoot** [comment]
Close ?
