### ISSUE TITLE
Remote smtp servers need FQDN domain as delivery name

### ISSUE THREAD

**Issue by manalejandro** [zone-eu/zone-mta#265]
Issue related: https://github.com/nodemailer/wildduck/issues/252

If use `delivery.localHostname` variable like delivery, remote smtp servers tell that they need FQDN domain...

https://github.com/zone-eu/zone-mta/blob/master/lib/sender.js#L179
https://github.com/zone-eu/zone-mta/blob/master/lib/sender.js#L947
https://github.com/zone-eu/zone-mta/blob/master/lib/sender.js#L1254

I need to hardcode these lines with my domain to work, thanks

**Comment by louis-lau** [comment]
I believe it uses whatever you specify in your ip pool configuration. Like Andris mentioned in the issue you referenced:
"See the ZoneMta pool config file to set the hostname (/etc/zone-mta/pools.toml)"

Here it is:
https://github.com/zone-eu/zone-mta-template/blob/master/config/pools.toml#L10

No need to hardcode anything.

**Comment by manalejandro** [comment]
Using that config:
```
[[default]]
address="0.0.0.0"
name="manalejandro.com"
```
still appears in logs src=172.200.0.103 that is my container ip not the domain

**Comment by louis-lau** [comment]
> still appears in logs src=172.200.0.103

What logs?

**Comment by manalejandro** [comment]
zonemta logs like:
```
DEFERRED from=fail2ban@manalejandro.com to=abuse@ovh.net src=172.200.0.103 mx=mx1.ovh.net[188.165.47.122]
```

**Comment by louis-lau** [comment]
Ah. That sounds like it working exactly like it's supposed to. That just means the zonemta is using the interface with ip `172.200.0.103` for sending.

If it's only logs I don't see the problem.

**Comment by andris9** [comment]
@louis-lau +1
ZoneMta has no way to know how your IP gets actually routed so it can only log what what was configured

**Comment by manalejandro** [comment]
Now works well :smile: sorry for my warnings, regards

**Comment by louis-lau** [comment]
No worries, glad it's working well 😁

**Comment by manalejandro** [comment]
:nerd_face: thanks
