### ISSUE TITLE
2.4.3 mongo warning log

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#267]
Since upgrading to 2.4.3 some i see lots of mongo warning in the logs:
```
Mar  9 21:31:52 s1 zone-mta: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
Mar  9 21:31:52 s1 zone-mta: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
```

**Comment by mailbaby** [comment]
I am seeing the same with an additional:

(node:48743) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency

**Comment by andris9** [comment]
```
(node:48743) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
```

this is conflict between node and mongo driver, it does not mean much and will go away with future updates

```
Mar  9 21:31:52 s1 zone-mta: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
```

This should get fixed with next release. It is not affecting anything just yet, especially if you do not use replicated MongoDB.

**Comment by dazoot** [comment]
Seems ok lately.
