### ISSUE TITLE
Accessing non-existent property 'MongoError' of module exports inside circular dependency

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [zone-eu/zone-mta#269]
Hello,

We are trying to setup mail server ( Wildduck + Haraka + ZoneMTA )in kubernetes; When we deployed Zone-MTA pod we are getting MongoError in logs as 
`(node:357) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency`

Also, we get this in logs:
```
info Initiating Domain Restriction Plugin
Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
```

**Comment by andris9** [comment]
You can discard these messages, these will be removed from future versions.
