### ISSUE TITLE
ZoneMTA as load-balancer for Mailcow-Servers

### ISSUE THREAD

**Issue by bennet-esyoil** [zone-eu/zone-mta#270]
Hello,

we are using ZoneMTA to route mails based on Header-values to two different Mailcow Instances. So we have a plugin-hook setup that adds a Zone-Header based on another header and the zones have different hosts and ports in the configuration.

That setup works beautifully for us, but we are in the need to track bounces (soft, but also hard-bounces) and make changes accordingly in our DB. Since zonemta offers the plugin-system, I want to use that to capture bounces and call other apis, so I can do the DB-update there.

Only problem atm is that the bounces are not being communicated back to zonemta. I don't know if this is a configuration problem on the mailcow's postfix side of things or something in zonemta, so i'd be glad if someone can help me here. 

If I forgot to provide any information please let me know, i'll do my best to provide that.

**Comment by louis-lau** [comment]
As zonemta is not the actual sending MTA in this scenario, it will not be handling the response of the recipient server, but the response of your postfix server. If your postfix server successfully receives the message, zonemta is completely done with the message.

If you want zonemta to handle the recipient server bounces, it needs to be sending to the actual recipient server.

**Comment by bennet-esyoil** [comment]
Yeah, i figured that out already.. The messages get queued in postfix so I understand that zonemta is done with them. I was thinking if there is any way to have them being queued in postfix, but still not being marked as sent in zonemta? Is that possible with some configuration on the postfix side?

**Comment by andris9** [comment]
What I have done in the past is to tail Postfix mail log and then update message state in DB if Postfix bounced that message.

**Comment by bennet-esyoil** [comment]
@andris9 I was thinking about that too, but it would be much nicer to have that only in one place, without having to manually manage scripts on two servers.. 

So a postfix solution to redirect bounces back would make the most sense to me, but if there's nothing I have to resort to other ways..

**Comment by louis-lau** [comment]
Unfortunately that's just not how bounces work. They are just return codes from the server at the other end. And then postfix sends a non delivery report to the original sender. There is nothing to be redirected :)

I assume there's a good reason you're not using zonemta to send directly?

**Comment by bennet-esyoil** [comment]
kind of.. We have boxes at our hoster with dedicated sending IPs to keep our sending-score clean and then the zonemta in AWS which takes care of distributing by type. So we have one sender for transactional emails and one for promo and all other.

One could use zonemta with both ips, but we loose redundancy with that and the option to route emails over another server if needed. 


I was hoping for a solution where one can tell postfix to not respond with "queued" at all, so that the emails state is the same in zonemta and postfix.

**Comment by louis-lau** [comment]
> but we loose redundancy with that

zonemta is especially designed with high availability in mind. You can connect multiple instances to the same database, and assign each specific zones. When a message is queued in zonemta it inserts it into the database, and then the correct instance of zonemta will pick it up for sending.

You can even have an instance of zonemta that only accepts and queues messages, but doesn't send them. Or instances that don't accept but only send. As long as they're connected to the same database the instances will work together.

I haven't (yet) done this, but that is how I understand the workings of zonemta.

> where one can tell postfix to not respond with "queued" at all

I suppose that would be more of a question for postfix instead of zonemta ;)
