### ISSUE TITLE
Mailcow custom plugin for DKIM 

### ISSUE THREAD

**Issue by bengivre** [zone-eu/zone-mta#272]
Hello there, 

I am trying to create a new module to get DKIM key from a Mailcow server using HTTP API request.
I am able to get my plugin running, based on few examples provided but zone-mta is not signing anything. 
A little bit of help will be nice :) 

Plugin is located in :  **zone-mta-template/plugins**

Configuration file is correctly loaded and working : 
**zone-mta-template/config/plugins/mailcow-dkim.toml**

With the following content : 
```
[mailcow-dkim]
enabled="sender"
```

The module has the correct hooks I believe : 

```
module.exports.title = 'Mailcow-Dkim';
module.exports.init = function (app, done) {
app.addHook('sender:connection', (delivery, options, next) => {
```

And the DKIM key information pushed to the array : 

```
                delivery.dkim.keys.push({
                        domainName: fromDomain,
                        keySelector: dkimKey.dkim_selector,
                        privateKey: dkimPrivateKey
                });
```

But still, none of the email is signed.
Should I enable something else in the main config file ? I did not change/add anything else than the plugin and the plugin configuration. 

Here you can see the logs from Zone-Mta : 

```
info Plugins/sender/46457 Initialized Mailcow-Dkim from <plugins/mailcow-dkim> [load time 0ms]

info Mailcow-Dkim/API - Looking for DKIM key for domain: example.com
info Mailcow-Dkim/API - Status Code: 200
info Mailcow-Dkim/API - Date in Response header: Sun, 25 Jul 2021 22:54:13 GMT
info Mailcow-Dkim/API - Reading response completed.
info Mailcow-Dkim/API - Got DKIM key for domain: example.com, KeyLength: 2048, DkimSelector: default, privatekey: -----BEGIN RSA PRIVATE KEY-----
[...]
```
Then the SMTP of the destination just accept the email and I cannot see any dkim signature

Thanks a lot for your help 
Regards,

**Comment by andris9** [comment]
Did you try to send an email to some of your own addresses? Did these messages receive without the signature?

**Comment by bengivre** [comment]
My test is sending an email from my personal domain to a gmail address. 
On the GMAIL side, I cannot see any signatures.

Maybe here is not the right place for the issue as I used zone-mta-template. Just FYI

**Comment by andris9** [comment]
I added a simple self contained DKIM plugin example for zone-mta-template.

Enable the plugin [here](https://github.com/zone-eu/zone-mta-template/blob/eaa1fd9bc790b652b9ea9d0f03f6a710207394cc/config/plugins/example-dkim.toml#L2). Source can be found [here](https://github.com/zone-eu/zone-mta-template/blob/master/plugins/example-dkim.js).

First try out if this plugin works for you, you don't even have to modify anything (except enabling the plugin in the config file). It does not matter if the domain name and selector are wrong, at first you just want to see if you get the DKIM-signature header to the message or not. Once you can verify that it works you can then modify it for your own use case.

**Comment by bengivre** [comment]
Thanks for the example. 
I tried the plugin, the result is identical. 

There is no signature added. 
Therefore I can see the log saying (with this example) :  
`info DKIM 17ae2c578820000aab.001 Added DKIM key for example.com `

Even in Silly mode logging, there is no information about signing or anything related to DKIM.

**Comment by bengivre** [comment]
Is there anything else I can try ? I believe this should work "out if the box" . If There's nothing else than enabling the plugin , i don't see what can I try. 

thanks

**Comment by bengivre** [comment]
@andris9 are you sure this works on a vanilla install ? Because it doesn't on my side. 
I deleted everything , install again, no luck

**Comment by bengivre** [comment]
I was able to see that it's working with you "demo-key" but not with mine. 
It looks like you are using a 1024 bit key and mine is 2048 
Do you think it can be the issue ? @andris9  ?

**Comment by andris9** [comment]
Any key size works as zone-mta does not care about the size. If it does not work then there might be something wrong with the key itself. Zone-mta passes that key directly to the Node.js [Sign class](https://nodejs.org/api/crypto.html#crypto_class_sign). Unfortunately signing error is not logged, if you want to see it then edit `node_modules/zone-mta/lib/dkim-sign.js` line 48 and add `console.log(E);` before the `return` statement.
