### ISSUE TITLE
Blacklist back-off - Configure the blacklist time period 

### ISSUE THREAD

**Issue by bengivre** [zone-eu/zone-mta#274]
Hi there ,

**In the documentation it says :** 
If the bounce occured because your sending IP is blacklisted then this IP gets disabled for that MX for the next 6 hours and message is retried from a different IP. You can also disable local IP addresses permanently for specific domains with disabledAddresses option.

From what I can see, the IP is blacklisted but not for long (1h) 

Aug  3 15:59:42 relay01 node[74185]: info Blacklist 17b0c500efe0003842.001 ADDBLADDRESS Blacklisting IP 116.202.182.33 for example.com
Aug  3 16:59:42 relay01 node[74185]: info Blacklist 17b0c500efe0003842.001 DELBLADDRESS De-blacklisting IP 116.202.182.33 for example.com

So it is an hour, from what I can tell. 
Is there a way to change that ?

Thanks

**Comment by andris9** [comment]
You can find the config option [here](https://github.com/zone-eu/zone-mta/blob/master/config/default.js#L463)
