### ISSUE TITLE
Multiple ZoneMTA and one Mongo and Avast.

### ISSUE THREAD

**Issue by huglester** [zone-eu/zone-mta#275]
Hello

So I will open MongoDB on all interfaces, protect with password/firewall for IP whitelist to connect to mongo.
change:
  instanceId= to something unique per instance.

Its only two changes required here? 
--
But what about Avast?
It uses socket also, so listening on public interfaces, won't just help? 
I would need Avast on all ZoneMTA installs?

**Comment by andris9** [comment]
I think that avast uses unix sockets, not tcp sockets so you would have to have Avast running on each ZoneMTA server where you accept emails for delivery.
