### ISSUE TITLE
ZoneMTA - npm start hanging up on line Initialized Stats Counter from <node_modules/zonemta-delivery-counters>

### ISSUE THREAD

**Issue by ChandanP1994** [zone-eu/zone-mta#281]
I am trying to install Zonemta in ubuntu VPS but during the npm start process hanged on : 
" Initialized Stats Counter from <node_modules/zonemta-delivery-counters> " 

Operating System : Ubuntu 18.04.
Nodejs Version : v12.22.6
NPM Version : 7.24.1
Redis Version : Redis server v=6.2.5

root@zonemta:~/zone-mta-template# npm start

> ansi-regex@5.0.1 start
> node index.js --config=config/zonemta.toml

info App  ---------------------------------------------------------------
info App
info App  ███████╗ ██████╗ ███╗   ██╗███████╗███╗   ███╗████████╗ █████╗
info App  ╚══███╔╝██╔═══██╗████╗  ██║██╔════╝████╗ ████║╚══██╔══╝██╔══██╗
info App    ███╔╝ ██║   ██║██╔██╗ ██║█████╗  ██╔████╔██║   ██║   ███████║
info App   ███╔╝  ██║   ██║██║╚██╗██║██╔══╝  ██║╚██╔╝██║   ██║   ██╔══██║
info App  ███████╗╚██████╔╝██║ ╚████║███████╗██║ ╚═╝ ██║   ██║   ██║  ██║
info App  ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝     ╚═╝   ╚═╝   ╚═╝  ╚═╝
info App
info App  ------------------------ zone-mta@3.2.2 -----------------------
info App
(node:4045) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
info SMTP/feeder SMTP feeder MTA server started listening on port 2525
info QS Queue server started
info API API server started
info Redis/4045 Redis ready to take connections
info mongo Setup 10 indexes
info Queue Sending queue initialized
info Child/default/4064 [431d483b484e151d0f0a] Spawning sender process for default
info Redis/4058 Redis ready to take connections
info Plugins/receiver/4058 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 8ms]
info Plugins/receiver/4058 Initialized Image Hashes from <node_modules/zone-mta/plugins/core/image-hashes> [load time 1ms]
info SMTP/feeder/4058 2 plugins loaded
info Redis/4058 Redis ready to take connections
info SMTP/feeder/4058 SMTP feeder MTA server started
info DNS/4064 Loaded DNS cache
info Sender/default/4064 [431d483b484e151d0f0a] Starting sending for default
info ConnPool/4064 Connection pool is ready to take connections
info Redis/4064 Redis ready to take connections
info Plugins/sender/4064 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 7ms]
info Plugins/sender/4064 Initialized Loop Breaker from <node_modules/zonemta-loop-breaker> [load time 1ms]
info Plugins/sender/4064 Initialized Limiter from <node_modules/zonemta-limiter> [load time 2ms]
info Child/bounces/4082 [0b8cb0ac563a08ccd726] Spawning sender process for bounces
info DNS/4082 Loaded DNS cache
info Sender/bounces/4082 [0b8cb0ac563a08ccd726] Starting sending for bounces
info ConnPool/4082 Connection pool is ready to take connections
info Redis/4082 Redis ready to take connections
info Plugins/sender/4082 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 8ms]
info Plugins/sender/4082 Initialized Loop Breaker from <node_modules/zonemta-loop-breaker> [load time 1ms]
info Plugins/sender/4082 Initialized Limiter from <node_modules/zonemta-limiter> [load time 2ms]
info Child/routed/4094 [48293aa26977fe8e5603] Spawning sender process for routed
info DNS/4094 Loaded DNS cache
info Sender/routed/4094 [48293aa26977fe8e5603] Starting sending for routed
info ConnPool/4094 Connection pool is ready to take connections
info Redis/4094 Redis ready to take connections
info Plugins/sender/4094 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 8ms]
info Plugins/sender/4094 Initialized Loop Breaker from <node_modules/zonemta-loop-breaker> [load time 1ms]
info Plugins/sender/4094 Initialized Limiter from <node_modules/zonemta-limiter> [load time 1ms]
info Plugins/main/4045 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 7ms]
info Plugins/main/4045 Initialized Email Bounce Notification from <node_modules/zone-mta/plugins/core/email-bounce> [load time 0ms]
info Plugins/main/4045 Initialized Stats Counter from <node_modules/zonemta-delivery-counters> [load time 39ms]

Please someone check and let me know the solution for this.
Thanks.

**Comment by andris9** [comment]
The application did not hang up, it is waiting for emails to be processed. In general ZoneMTA is running and can be used once you see `MTA server started` like you have here:

```
info SMTP/feeder/4058 SMTP feeder MTA server started
```

**Comment by ChandanP1994** [comment]
Thanks a lot man @andris9 for clarification, 
one more question I have : I can not use the server if I started the npm start command, and it will be on running mode if I close the process via ctl+c ?

**Comment by andris9** [comment]
In general you should run ZoneMTA as a service (that means it runs as a background process and not as an active application). There are tons of different options for doing so and it also depends on the operating system etc. For example, here's a tutorial of how to run Node.js apps as pm2 services: https://fitdevops.in/how-to-setup-pm2-and-run-node-js-applications/

**Comment by ChandanP1994** [comment]
Ok, 
sorry the multiple questions from my side. 
Could you please help me : How may I the run the ZoneMTA service in background. 

Should I configure pm2 service for running ZoneMTA in background ?

**Comment by andris9** [comment]
Well, it depends on your system. I'd suggest you to google the topic of running applications as services and reading tutorials about it to understand how these things work. pm2 is only one of the options of doing so.
