### ISSUE TITLE
Shortcut to send message from a plugin

### ISSUE THREAD

**Issue by matteomattei** [zone-eu/zone-mta#288]
I need to send a message to the administrator (or to the client) from a plugin when some circumstances occur (for example when the user reach the limit of messages sent per day).
Obviously I can use nodemailer with a transport using localhost as smtp server, but I am wondering if there is some sort of internal (and undocumented) zone-mta function to do it.

**Comment by dazoot** [comment]
Nope. Nothing internal. Just send a normal mail via SMTP or via API like mentioned here:
https://github.com/zone-eu/zone-mta#http-api

Close ?

**Comment by matteomattei** [comment]
Got it, thanks.
We can close it.
