### ISSUE TITLE
Support setting instanceId from env variable?

### ISSUE THREAD

**Issue by taxilian** [zone-eu/zone-mta#292]
Hi,

I'm setting up zonemta in a kubernetes environment; because of that it is really easy to scale up and down how many instances are running, which I'd mostly do for high availability purposes =] That said, it's much more difficult to provide a unique instanceId for each in a configuration file than it would be if I could override it in an environment variable =]

Would it be possible to add support for e.g ZMTA_INSTANCEID or similar as an environment variable that if set it would use that value instead of whatever is in the config file -- or alternatively use that unless something is in the config file?

Seems like an easy tweak but it would simplify my life greatly =]

**Comment by andris9** [comment]
It's actually been a long-requested feature. When I started with ZoneMTA and the other related projects back in 2016, deploying applications using docker or Kubernetes was not so common and the more traditional approaches mainly used config files and command-line arguments, not environment variables. So at that time, I did not really think about environment variable support and did not implement it. This is why you can't use the requested approach with ZoneMTA right now. With my other projects (eg. [https://emailengine.app/](https://emailengine.app/)) I have moved to use environment variables as well for configuration, so I would need to port those changes to ZoneMTA and WildDuck. Can't give any ETA though.

**Comment by taxilian** [comment]
Do you have a specific idea of how you want to see it done? I just made
https://github.com/zone-eu/zone-mta/pull/294 which fixes this for me (I'm
using it now and just dropping the pod name in the variable). It'd be nice
to have a more complete env-based way to override configuration, but at the
moment I can't find any other variables that need to be different for
different instances, so this removes my need to completely change my
configuration method just to override one value ;-)
