### ISSUE TITLE
Fallback to MTA

### ISSUE THREAD

**Issue by netweaveruk** [zone-eu/zone-mta#295]
Hi,
After all my local IP addresses have been exhausted when sending an email, rather than bouncing I'd like to fall back to an external MTA (MailChannels to be precise).
Would anyone be willing to help me with how to configure this please, as I'm struggling?
Thanks

**Comment by Luskan777** [comment]
Hi,

I'm trying to solve the same problem, my attempt to solve this is to change the send zone after certain send attempts, if it has an X value of attempts it routes to another zone that has a relayhost for the MailChannel.

I think I can get the value of attempts by the value "_deferred: count: X" in the bank, and change the zone by the value "sendingZone: X"

I'm trying to do this through the code left as an example:

```
app.addHook('sender:headers', (delivery, connection, next) => {
    if (!delivery.updates) {
        // make sure the updates object exists
        delivery.updates = {};
    }
    // override Zone for this message if it is deferred, no effect if message bounces or is accepted
    delivery.updates.sendingZone = 'someother';

    next();
});
```

I still haven't been able to, but as soon as I finish I'll let you know, if anyone from the community wants to help me develop this plugin, I'd be very grateful

**Comment by netweaveruk** [comment]
This is fantastic @Luskan777, thank you.  

Running on a test server now and is working perfectly so far.
