### ISSUE TITLE
Sending attempt limit

### ISSUE THREAD

**Issue by Luskan777** [zone-eu/zone-mta#298]
Hi,

I have a simple question regarding the mail queue and sending attempts when a certain send fails for dns or network reasons.

![Captura de Tela_Área de Seleção_20220204105041](https://user-images.githubusercontent.com/71342479/152540534-4870b3e6-404e-4abb-a0ff-b6c914cd8e01.png)

In this example above, I tried to send an email to a non-existent domain on purpose, it seems the email hangs in the queue, and doesn't return any bouced.
I was wondering if there is a limit on attempts.
 I'm new to zone-mta, so I don't know if there's a limit, as I'm worried that it generates a loop, in which it overloads the mail queue, causing several "DEFERRED"

forgive my english :)

**Comment by louis-lau** [comment]
Your english is fine! A DNS error is not a permanent error, as it could only be temporary. So the message is deferred and retried later. I will retry at this interval:
https://github.com/zone-eu/zone-mta/blob/5c9a427580821c835091261af401c8e1f3d7d6a4/lib/sender.js#L26-L44

After the final try at 48h it will bounce permanently.

**Comment by Luskan777** [comment]
Perfect!!

Good to know that it sets a limit and that I can change it, really, I never waited 48 hours to know if it would send a permanent bouced.

Your answer solves my doubt, thank you very much, I will close this issue
