### ISSUE TITLE
Pre-init failure high CPU+MEM usage

### ISSUE THREAD

**Issue by jtagcat** [zone-eu/zone-mta#305]
Might be interested in https://github.com/nodemailer/wildduck-dockerized/issues/18, specifically high CPU+MEM usage before it starts / fails and restarts in loop.

_* proovisin meiliserverit unise peaga üles tulistada, ei ole veel päris kindel, kas tulistas vastu või tulistasin ennast_

**Comment by dazoot** [comment]
Seems a mongo connection issue which makes Zonemta to retry connect. Better fix your mongo connection issue instead of posting this weird bug :)

Please close.

We have no such issue with Zonemta and we are sending millions / day.
Upgrading mongo primary always helps. RAM / CPU / NVME.
