### ISSUE TITLE
Share load between a mix of IPv4 and IPv6 addresses

### ISSUE THREAD

**Issue by ghost** [zone-eu/zone-mta#307]
Is it possible to have a sending pool containing both v4 and v6 addresses that ZoneMTA will share the load between?

My best understanding is that this isn't possible at the moment, and that depending on the value of `preferIP6` ZoneMTA will always try to use either v4 or v6 addresses.

A particular issue I'm dealing with at the moment is wanting to warm up a new v6 address, but can only configure ZoneMTA to either send (essentially) all or (essentially) none of the messages via this new address.

**Comment by louis-lau** [comment]
I don't think that that's currently possible. You could however create a plugin that routes for example 10% of messages to a special IPv6 zone with math.random().
