### ISSUE TITLE
450 Failed to resolve IP address for mailhog of the MX server

### ISSUE THREAD

**Issue by Thanoonazad** [zone-eu/zone-mta#318]
Hi, I have installed mailhog, zonemta-api, zonemta-mongo and zonemta-redis on docker kubernetes and I got this error when I send an email. Can you please help me?

```
info Sender/default/34[3] 1845c2a47ee0003425.001 CONNECTING domain=hptestdomain port=1025 
ERR! Sender/default/34[3] 1845c2a47ee0003425.001 ERRCONNECT domain=hptestdomain error=queryA ESERVFAIL mailhog 
info Sender/default/34[3] 1845c2a47ee0003425.001 DEFERRED[dns] from=admin@hptestdomain to=test1@hptestdomain src= mx=hptestdomain id=<edf87c36-4d30-318b-a948-db033adb49db@hptestdomain> (450 Failed to resolve IP address for mailhog of the MX server for hptestdomain. DNS server returned general failure) 
```

**Comment by andris9** [comment]
Zone-MTA can not resolve the MX domain name `hptestdomain`. Use a valid domain name that is resolvable via DNS (not via hosts file etc)

**Comment by Thanoonazad** [comment]
I did try to use for a local installation but it didn't work!
Is there any way to disable the MX domain resolve? 
@andris9 Thank you

**Comment by andris9** [comment]
No, ZoneMTA connects to MX servers, and this assumes it can resolve MX records. You could add some subdomain records that point to 127.0.0.1 if you want to use it for local addresses.

**Comment by Thanoonazad** [comment]
Do you mean in the domains.toml config?
Ok cool. Thank you again @andris9
