### ISSUE TITLE
questions: is `requireTLS` and `opportunisticTLS` options incorrect?

### ISSUE THREAD

**Issue by titanism** [zone-eu/zone-mta#323]
Briefly mentioned in an email to you @andris9 &ndash; but filing the issue here on GitHub.

I noticed you are missing `requireTLS: enforceTLS` option altogether, and the option for `opportunisticTLS: !!enforceTLS` is incorrect, as it should instead be `oppportunisticTLS: !Boolean(enforceTLS)` (the inverse of boolean).

<https://github.com/zone-eu/zone-mta/blob/5daa48eea4aa05e724eb2ab80fd3a957e6cc8c6c/lib/sender.js#L1103>

**Comment by andris9** [comment]
`requireTLS` is intentionally missing, to detect policy violation if a MITM removes the STARTTLS extension: https://github.com/zone-eu/zone-mta/blob/5daa48eea4aa05e724eb2ab80fd3a957e6cc8c6c/lib/sender.js#L1271

**Comment by andris9** [comment]
`opportunisticTLS` option seems to be invalid, or rather - it has no effect right now. I think I need to fix it to `true` 🤔
