### ISSUE TITLE
Zone Stops Working or Gets Disabled

### ISSUE THREAD

**Issue by maileroo** [zone-eu/zone-mta#347]
We are encountering an odd issue.

It seems that one of our zones got disabled and all the emails marked to be sent through it just got QUEUED, but never sent. We noticed this after 24 hours and simply restarted ZoneMTA and then it quickly sent all the emails after.

This is the only log related to one of the messages that we sent. As you can see, there is no further messages related to the message such as CONNECTING, CONNECTED and ACCEPTED.

info Queue/49268 id=6deev573jitmclvk 18b08798119000097b QUEUED (message-id=<367296783080074593559926.9761.20231076512@mail.XXXXX.com> from=no.reply@mail.XXXXX.com to=XXXX@gmail.com src=127.0.0.1 subject="XXXX" body=529 md5=c5d4edfb7bfb)

Do you have any ideas what could be wrong?

**Comment by maileroo** [comment]
Just happened again on two servers. All zones stuck and just queuing emails.

# HELP zonemta_delivery_status Delivery status
# TYPE zonemta_delivery_status counter
zonemta_delivery_status{status="delivered"} 161
zonemta_delivery_status{status="deferred"} 5
zonemta_delivery_status{status="rejected"} 2

# HELP zonemta_message_push Messages pushed to queue
# TYPE zonemta_message_push counter
zonemta_message_push{result="success"} 241

# HELP zonemta_bounce_generation Bounce generation
# TYPE zonemta_bounce_generation counter
zonemta_bounce_generation 2

# HELP zonemta_message_drop Messages dropped
# TYPE zonemta_message_drop counter
zonemta_message_drop 0

# HELP zonemta_connection_reuses Connection reuses
# TYPE zonemta_connection_reuses counter
zonemta_connection_reuses 7

# HELP zonemta_connection_pool_size Connection Pool Size
# TYPE zonemta_connection_pool_size gauge
zonemta_connection_pool_size 0

# HELP zonemta_queue_size Current size of the queue
# TYPE zonemta_queue_size gauge
zonemta_queue_size{type="queued"} 202
zonemta_queue_size{type="deferred"} 0

# HELP zonemta_blacklisted Blacklisted addresses
# TYPE zonemta_blacklisted gauge
zonemta_blacklisted 0

# HELP process_cpu_user_seconds_total Total user CPU time spent in seconds.
# TYPE process_cpu_user_seconds_total counter
process_cpu_user_seconds_total 1486.886662

# HELP process_cpu_system_seconds_total Total system CPU time spent in seconds.
# TYPE process_cpu_system_seconds_total counter
process_cpu_system_seconds_total 729.607429

# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2216.494091

# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1696654350

# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 103526400

# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1070710784

# HELP process_heap_bytes Process heap size in bytes.
# TYPE process_heap_bytes gauge
process_heap_bytes 122392576

# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 63

# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 65535

# HELP nodejs_eventloop_lag_seconds Lag of event loop in seconds.
# TYPE nodejs_eventloop_lag_seconds gauge
nodejs_eventloop_lag_seconds 0

# HELP nodejs_eventloop_lag_min_seconds The minimum recorded event loop delay.
# TYPE nodejs_eventloop_lag_min_seconds gauge
nodejs_eventloop_lag_min_seconds 0.008871936

# HELP nodejs_eventloop_lag_max_seconds The maximum recorded event loop delay.
# TYPE nodejs_eventloop_lag_max_seconds gauge
nodejs_eventloop_lag_max_seconds 0.018546687

# HELP nodejs_eventloop_lag_mean_seconds The mean of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_mean_seconds gauge
nodejs_eventloop_lag_mean_seconds 0.010057442780107192

# HELP nodejs_eventloop_lag_stddev_seconds The standard deviation of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_stddev_seconds gauge
nodejs_eventloop_lag_stddev_seconds 0.0001584724936002402

# HELP nodejs_eventloop_lag_p50_seconds The 50th percentile of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_p50_seconds gauge
nodejs_eventloop_lag_p50_seconds 0.010067967

# HELP nodejs_eventloop_lag_p90_seconds The 90th percentile of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_p90_seconds gauge
nodejs_eventloop_lag_p90_seconds 0.010067967

# HELP nodejs_eventloop_lag_p99_seconds The 99th percentile of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_p99_seconds gauge
nodejs_eventloop_lag_p99_seconds 0.010657791

# HELP nodejs_active_resources Number of active resources that are currently keeping the event loop alive, grouped by async resource type.
# TYPE nodejs_active_resources gauge
nodejs_active_resources{type="PipeWrap"} 12
nodejs_active_resources{type="TCPServerWrap"} 3
nodejs_active_resources{type="TCPSocketWrap"} 21
nodejs_active_resources{type="ProcessWrap"} 11
nodejs_active_resources{type="Timeout"} 1
nodejs_active_resources{type="Immediate"} 1

# HELP nodejs_active_resources_total Total number of active resources.
# TYPE nodejs_active_resources_total gauge
nodejs_active_resources_total 49

# HELP nodejs_active_handles Number of active libuv handles grouped by handle type. Every handle type is C++ class name.
# TYPE nodejs_active_handles gauge
nodejs_active_handles{type="Socket"} 24
nodejs_active_handles{type="Server"} 3
nodejs_active_handles{type="ChildProcess"} 11
nodejs_active_handles{type="Pipe"} 9

# HELP nodejs_active_handles_total Total number of active handles.
# TYPE nodejs_active_handles_total gauge
nodejs_active_handles_total 47

# HELP nodejs_active_requests Number of active libuv requests grouped by request type. Every request type is C++ class name.
# TYPE nodejs_active_requests gauge

# HELP nodejs_active_requests_total Total number of active requests.
# TYPE nodejs_active_requests_total gauge
nodejs_active_requests_total 0

# HELP nodejs_heap_size_total_bytes Process heap size from Node.js in bytes.
# TYPE nodejs_heap_size_total_bytes gauge
nodejs_heap_size_total_bytes 37388288

# HELP nodejs_heap_size_used_bytes Process heap size used from Node.js in bytes.
# TYPE nodejs_heap_size_used_bytes gauge
nodejs_heap_size_used_bytes 31735960

# HELP nodejs_external_memory_bytes Node.js external memory size in bytes.
# TYPE nodejs_external_memory_bytes gauge
nodejs_external_memory_bytes 20692121

# HELP nodejs_heap_space_size_total_bytes Process heap space size total from Node.js in bytes.
# TYPE nodejs_heap_space_size_total_bytes gauge
nodejs_heap_space_size_total_bytes{space="read_only"} 0
nodejs_heap_space_size_total_bytes{space="new"} 1048576
nodejs_heap_space_size_total_bytes{space="old"} 30019584
nodejs_heap_space_size_total_bytes{space="code"} 2883584
nodejs_heap_space_size_total_bytes{space="shared"} 0
nodejs_heap_space_size_total_bytes{space="new_large_object"} 0
nodejs_heap_space_size_total_bytes{space="large_object"} 3436544
nodejs_heap_space_size_total_bytes{space="code_large_object"} 0
nodejs_heap_space_size_total_bytes{space="shared_large_object"} 0

# HELP nodejs_heap_space_size_used_bytes Process heap space size used from Node.js in bytes.
# TYPE nodejs_heap_space_size_used_bytes gauge
nodejs_heap_space_size_used_bytes{space="read_only"} 0
nodejs_heap_space_size_used_bytes{space="new"} 906704
nodejs_heap_space_size_used_bytes{space="old"} 25213680
nodejs_heap_space_size_used_bytes{space="code"} 2290048
nodejs_heap_space_size_used_bytes{space="shared"} 0
nodejs_heap_space_size_used_bytes{space="new_large_object"} 0
nodejs_heap_space_size_used_bytes{space="large_object"} 3350744
nodejs_heap_space_size_used_bytes{space="code_large_object"} 0
nodejs_heap_space_size_used_bytes{space="shared_large_object"} 0

# HELP nodejs_heap_space_size_available_bytes Process heap space size available from Node.js in bytes.
# TYPE nodejs_heap_space_size_available_bytes gauge
nodejs_heap_space_size_available_bytes{space="read_only"} 0
nodejs_heap_space_size_available_bytes{space="new"} 124176
nodejs_heap_space_size_available_bytes{space="old"} 4228184
nodejs_heap_space_size_available_bytes{space="code"} 412784
nodejs_heap_space_size_available_bytes{space="shared"} 0
nodejs_heap_space_size_available_bytes{space="new_large_object"} 1048576
nodejs_heap_space_size_available_bytes{space="large_object"} 0
nodejs_heap_space_size_available_bytes{space="code_large_object"} 0
nodejs_heap_space_size_available_bytes{space="shared_large_object"} 0

# HELP nodejs_version_info Node.js version info.
# TYPE nodejs_version_info gauge
nodejs_version_info{version="v20.6.1",major="20",minor="6",patch="1"} 1

# HELP nodejs_gc_duration_seconds Garbage collection duration by kind, one of major, minor, incremental or weakcb.
# TYPE nodejs_gc_duration_seconds histogram
nodejs_gc_duration_seconds_bucket{le="0.001",kind="minor"} 161317
nodejs_gc_duration_seconds_bucket{le="0.01",kind="minor"} 161319
nodejs_gc_duration_seconds_bucket{le="0.1",kind="minor"} 161319
nodejs_gc_duration_seconds_bucket{le="1",kind="minor"} 161319
nodejs_gc_duration_seconds_bucket{le="2",kind="minor"} 161319
nodejs_gc_duration_seconds_bucket{le="5",kind="minor"} 161319
nodejs_gc_duration_seconds_bucket{le="+Inf",kind="minor"} 161319
nodejs_gc_duration_seconds_sum{kind="minor"} 41.07301212000938
nodejs_gc_duration_seconds_count{kind="minor"} 161319
nodejs_gc_duration_seconds_bucket{le="0.001",kind="incremental"} 185
nodejs_gc_duration_seconds_bucket{le="0.01",kind="incremental"} 185
nodejs_gc_duration_seconds_bucket{le="0.1",kind="incremental"} 185
nodejs_gc_duration_seconds_bucket{le="1",kind="incremental"} 185
nodejs_gc_duration_seconds_bucket{le="2",kind="incremental"} 185
nodejs_gc_duration_seconds_bucket{le="5",kind="incremental"} 185
nodejs_gc_duration_seconds_bucket{le="+Inf",kind="incremental"} 185
nodejs_gc_duration_seconds_sum{kind="incremental"} 0.05982888436317442
nodejs_gc_duration_seconds_count{kind="incremental"} 185
nodejs_gc_duration_seconds_bucket{le="0.001",kind="major"} 0
nodejs_gc_duration_seconds_bucket{le="0.01",kind="major"} 185
nodejs_gc_duration_seconds_bucket{le="0.1",kind="major"} 185
nodejs_gc_duration_seconds_bucket{le="1",kind="major"} 185
nodejs_gc_duration_seconds_bucket{le="2",kind="major"} 185
nodejs_gc_duration_seconds_bucket{le="5",kind="major"} 185
nodejs_gc_duration_seconds_bucket{le="+Inf",kind="major"} 185
nodejs_gc_duration_seconds_sum{kind="major"} 0.31572437977790824
nodejs_gc_duration_seconds_count{kind="major"} 185

**Comment by maileroo** [comment]
{
    "zone": "all",
    "active": {
        "entries": [
            { "key": "bounces", "value": 0 },
            { "key": "zone_1", "value": 114 },
            { "key": "zone_2", "value": 88 }
        ],
        "rows": 202
    },
    "deferred": {
        "entries": [
            { "key": "bounces", "value": 0 },
            { "key": "zone_1", "value": 0 },
            { "key": "zone_2", "value": 0 }
        ],
        "rows": 0
    }
}

**Comment by maileroo** [comment]
Sorry to bother you, @andris9 

Do you have any ideas what could be wrong? It just suddenly stops processing the queue once a week and usually restarting the application works.

**Comment by maileroo** [comment]
```
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info Sender/zone_1/69694[15] id=[CENSORED] CONNECTING domain=[CENSORED] port=[CENSORED]
info Sender/zone_1/69694[15] id=[CENSORED] CONNECTED domain=[CENSORED] mx=[CENSORED] src=[CENSORED]
info Sender/zone_1/69694[15] id=[CENSORED] ACCEPTED from=[CENSORED] to=[CENSORED] src=[CENSORED] mx=[CENSORED] id=<[CENSORED]> ([CENSORED])
info Sender/zone_1/69649 All SMTP sessions end id=[CENSORED]
info Sender/zone_1/69694[15] id=[CENSORED] SMTPCLOSE [CENSORED] Connection closed response="[CENSORED]"
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69661 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69661 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
info SMTP/feeder/69662 CONNECTION id=[CENSORED] src=localhost[127.0.0.1]:[CENSORED]
info Queue/69662 id=[CENSORED] QUEUED (message-id=<[CENSORED]> from=[CENSORED] to=[CENSORED] src=127.0.0.1 subject="[CENSORED]" body=[CENSORED] md5=[CENSORED])
```

Here's what the logs look like.

**Comment by andris9** [comment]
Well, I'm not sure what is going on there. If this continues, I'd suggest you set a periodic cron job that restarts your ZoneMTA service

**Comment by maileroo** [comment]
Been trying to debug it, lately. Seems like the sender process gets stuck and never calls sendNext() again.

**Comment by maileroo** [comment]
I can confirm the issue was with one of my plugins. I had a plugin with a hook, but I never called next() in the plugin, so eventually this caused a meltdown after sending a large number of emails.

**Comment by louis-lau** [comment]
Thanks for posting your resolution!
