### ISSUE TITLE
npm start says [config/zonemta.toml] config/zonemta.toml: Expected "\n" but "_" found.

### ISSUE THREAD

**Issue by mtpltech** [zone-eu/zone-mta#351]
I followed the steps shared and setup the machine by installing and enabling redis, mongoDB and node in my machine 
I cloned the git $ git clone git://github.com/zone-eu/zone-mta-template.git
$ cd zone-mta-template
$ npm install eslint --save-dev
$ npm init
$ npm install --production
$ npm start
After I run the app with npm start got the error 
PS C:\Data\zone-mta-template> npm start

> zone-mta-template@1.7.0 start
> node index.js --config=config/zonemta.toml

[config/zonemta.toml] config/zonemta.toml: Expected "\n" but "_" found.

is there any issue in the zonemta.toml file under config

**Comment by louis-lau** [comment]
I don't think zonemta was design with windows servers in mind. In this case I think it's the windows line endings of the config file. I'd recommend running it on a linux server. For development of plugins etc you could use WSL.

**Comment by mtpltech** [comment]
okay sure thanks will test with linux OS
