### ISSUE TITLE
List of Zone-MTA plugin that we made

### ISSUE THREAD

**Issue by pydubreucq** [zone-eu/zone-mta#352]
Hi,
I just would like to share list of Zone-MTA plugin that we created.
Maybe, they'll can use to someone :)

[zonemta-multi-dkim](https://github.com/Mindbaz/zonemta-multi-dkim) - Load & use a dkim key file based on a header value
[zonemta-auth-keycloak](https://github.com/Mindbaz/zonemta-auth-keycloak) - Authentication with Keycloak
[zonemta-auth-keycloak-token](https://github.com/Mindbaz/zonemta-auth-keycloak-token)  - Authentication with Keycloak token
[zonemta-block-zone](https://github.com/Mindbaz/zonemta-block-zone) - Block sending to specific zone(s)
[zonemta-dry-run](https://github.com/Mindbaz/zonemta-dry-run) - change zonemta mail receiver for testing purpose (With that you can reroute emails to your proper mail server)
[zonemta-auth-boundary](https://github.com/Mindbaz/zonemta-auth-boundary) - Authentication with Boundary (Hashicorp)

I hope that these plugins could help someone.
Maybe a page in the wiki for listing all Zone-MTA plugin made by the community can be cool :)

Bye

**Comment by andris9** [comment]
Great idea, created a [Plugins wiki page](https://github.com/zone-eu/zone-mta/wiki/Plugins)

**Comment by pydubreucq** [comment]
Thanks :)
