### ISSUE TITLE
I am very confused which one to install + Redis error

### ISSUE THREAD

**Issue by ravivgolov** [zone-eu/zone-mta#374]
Hello
I followed the guide, which explains to install the skeleton version, but the skeleton version missing for example the default.js file. and more files.

So which one to install?

Also, another error is:
ERR! Redis/15981 NOAUTH Authentication required.
ERR! Queue Could not initialize database: NOAUTH Authentication required.

I set the password in Redis, how to set the password in ZoneMTA?

**Comment by louis-lau** [comment]
default.js is just the default config that you override:
> Default configuration can be found from [default.js](https://github.com/zone-eu/zone-mta/blob/master/config/default.js). You can override options in your application specific configuration but you do not need to specify these values that you want to keep as default.

 How you override it is up to you, the zone-mta-template uses a toml config which is described pretty well here:
https://github.com/zone-eu/zone-mta-template?tab=readme-ov-file#configuration
> All configuration files reside in the config directory.

As the name implies, zone-mta-template is a template for creating your own zonemta setup.

**Comment by ravivgolov** [comment]
So basically, I need to install the template one as suggested in the guide and do the whole extra configuration I need?

**Comment by louis-lau** [comment]
There's also a config included with the template that you can start from. It's the sentence I quoted.

**Comment by andris9** [comment]
Zone-MTA is more like a framework and not an off-the-shelf software you can just download and run. You can build your specific system on top of it. For example, you can check how WildDuck uses ZoneMTA by implementing a custom plugin that handles all the required logic: https://github.com/nodemailer/zonemta-wildduck
