### ISSUE TITLE
PR request: include disabled zones in /zones api

### ISSUE THREAD

**Issue by skadefro** [zone-eu/zone-mta#380]
I would suggest updating http api /zone to also include disabled zones.
This could be relevant in multiple cases, but specifically i requests it to show mails and statistics in ZoneMTA web admin for disabled zones too.
I'm using the trick suggested in #287 so this would allow monitoring mails in hold.
We could also add a different property to a zone, that will not disable it but also make it stop processing, but disabled kind of covers that perfectly ?

**Comment by andris9** [comment]
Fixed with https://github.com/zone-eu/zone-mta/commit/fb826d6de294f23387b1fb4ef90ad20889779113 - added a query argument `includeDisabled`. If it is `"true"` then returns all zones
