### ISSUE TITLE
Any way to add entire subnet to outbound?

### ISSUE THREAD

**Issue by ravivgolov** [zone-eu/zone-mta#395]
Hello

Is there any way to add an entire subnet instead of a single IP?

**Comment by louis-lau** [comment]
A pool is an array of addresses. For an entire /24, just add 254 addresses.

**Comment by ravivgolov** [comment]
Not an easy task, do you mean like that:
`default=["1.2.3.3", "1.2.3.4", "1.2.3.4"]`

Another question, can I extract the rfc288 source email for inspection from the logs?

**Comment by louis-lau** [comment]
> Not an easy task, do you mean like that:
> default=["1.2.3.3", "1.2.3.4", "1.2.3.4"]

Yep! I feel like there are tools out there that can spit out every address in a subnet if you really need it. Sounds like a fairly easy task.

> Another question, can I extract the rfc288 source email for inspection from the logs?

Messages aren't kept after they're delivered, unfortunately. Not in the logs either, that would make for one huge log otherwise.

**Comment by ravivgolov** [comment]
Thanks,

Can I disable the logs to not save to mongo?

And this first time I see it:
"SMTP error from remote mail server after pipelined MAIL FROM: SIZE=37634: 452 Can not send from info@domain.com. Try again later."

Why he is blocked? with other MTA, he were able to send.

**Comment by ravivgolov** [comment]
I have no got the answer I am looking for.
