### ISSUE TITLE
Override 4xx with bounces.txt?

### ISSUE THREAD

**Issue by mxroute** [zone-eu/zone-mta#396]
I'm trying to override specific 4xx reactions to treat them as rejections. For example:

"450 User is receiving mail too quickly tnmpmscs"

And in bounces.txt:

`^450[ \-].* User is receiving mail too quickly,reject,recipient,Stop`

But it just keeps deferring it. I'm sure I'm doing something stupid, I just can't see it. Is this possible?

**Comment by andris9** [comment]
There's an extra space between `.*` and `User`, so the regex expects there to be 2 spaces in total which is not correct.

You can test your regexes with the check-bounces tool:

```
echo "450 User is receiving mail too quickly tnmpmscs" | node ./bin/check-bounce.js
```

This would give you the matching rule for that response message. Rules are processed from top to bottom, so if a rule with higher line nr matches it means your regex failed.
