### ISSUE TITLE
Pre-mature MX server lookup

### ISSUE THREAD

**Issue by jkramarz** [zone-eu/zone-mta#4]
In `feeder-server.js:116` MX lookup for rcpt is being performed. Receiving SERVFAIL from DNS message should be deferred rather than rejected: it's probably not sender's fault. If it's persistent fault, I'd expect a standard bounce.

**Comment by andris9** [comment]
I added a configuration option to allow resolving MX on RCPT TO (disabled by default) f4ee6626bf49151c6e74ef175782409ac6dfc5a0
