### ISSUE TITLE
Suppression list?

### ISSUE THREAD

**Issue by ravivgolov** [zone-eu/zone-mta#403]
Hello

I'd like to modify the Suppression list so that everyone on the list who is rejected will not be silently rejected, but will be rejected with a bounce, similar to the blacklist. Is there a setting for this, or do I need to update the code?

**Comment by louis-lau** [comment]
@ravivgolov Just fyi people watching the issues in this repo get emails when you open an issue. It's fine of course, but since you seek to open issues and the close them 10 minutes later, maybe next time wait 10 more minutes before opening the issue ;)
