### ISSUE TITLE
Enable to send from <>

### ISSUE THREAD

**Issue by ravivgolov** [zone-eu/zone-mta#407]
Hello

I am using another mail server to connect to zonemta. However, when that server generates a bounce message, it uses <> and zonemta rejects that(Sender can't be empty). How can I enable <> from that server?

**Comment by louis-lau** [comment]
I did ask you to think about it for 10 minutes longer the last time, before opening an issue. Can you actually do that next time? Instead of again opening an issue and then closing it 5 minutes later?
