### ISSUE TITLE
Routing based on sender domain and sub-domain

### ISSUE THREAD

**Issue by pydubreucq** [zone-eu/zone-mta#416]
Hi,
I would like to know if it's possible to route based on sender domain and sub-domain ?
I would like to block a sender domain and all their sub-domain.

I tried to use a wildcard but it don't work:

```
'sending-zone': {
    ...
    senderDomains: ['*.example.com']
}
```

Thanks by advance
Bye

**Comment by andris9** [comment]
It's an exact match check, so you would have to list all known subdomains in the list. Or write a plugin for the `queue:route` hook that sets it.
