### ISSUE TITLE
futureDate option

### ISSUE THREAD

**Issue by pydubreucq** [zone-eu/zone-mta#417]
Hi,
I discovered the futureDate option but I can't test it.

In the `/opt/zone-mta/config/default.js` file, I change value to **true**
I've restarted Zone-MTA to be sure that's ok.

I tried to send an email with swaks like that:

swaks --to my@address.io --from my@address.io --server my.server.io --port 2525 -tls --auth-user "john-doe" --auth-password "password" --h-Subject "Test delayed email" --body "Youpla Boom"  --header "Date: Mon, 12 Aug 2024 18:43:30 +0000"

My email was queued at 2024-08-12 18:23:40

In the Header, I can see the Date Header with the good hour:
`Date: Mon, 12 Aug 2024 18:24:30 +0000`

But Zone-MTA don't care of my Date header.

Have I made a mistake?

**Comment by louis-lau** [comment]
Is that actually the co fig you're using though? A usual zone-mta setup would use zone-mta-template as a starting point, which overrides that default config here

https://github.com/zone-eu/zone-mta-template/blob/2ec1ba85a44c4665a6326271c8162ee76c4d6d02/config/plugins/default-headers.toml#L6

**Comment by pydubreucq** [comment]
With default-headers.toml it works!
Thanks a lot
