### ISSUE TITLE
HTTP send

### ISSUE THREAD

**Issue by ravivgolov** [zone-eu/zone-mta#421]
Hello

How do I use the HTTP send when I have an auth user and password?

**Comment by louis-lau** [comment]
Please explain what you mean exactly. What are you trying to do? What have you tried? What's happening when you try?

**Comment by ravivgolov** [comment]
I am using the normal SMTP connection with the AUTH plugin, and I want to achieve the same with the HTTP API provided in zonemta core, but with AUTH. How can I do this?

**Comment by louis-lau** [comment]
You can use any authenticating reverse proxy for this. It can then set the X-Authenticated-User header.

**Comment by louis-lau** [comment]
Zone-mta wouldn't know the password for http. Only your reverse proxy would know that. A reverse proxy is something you put in front of another server. In this case the reverse proxy would handle authentication.

**Comment by louis-lau** [comment]
What that authentication looks like is completely up to you and your reverse proxy config. Could be basicauth, could be cookies, could be a custom header. Whatever you want to use and what your reverse proxy supports
