### ISSUE TITLE
Fail2ban/auto block connections DDoS attack and brute force

### ISSUE THREAD

**Issue by ravivgolov** [zone-eu/zone-mta#423]
Hello,

Recently, I noticed a significant DDoS and brute-force attack on my SMTP connection.

Do you have any options to filter failed attempts, such as using Fail2ban or another solution?

Haraka has something, but here I didn't find it.

Example:
```
info SMTP/SMTP-Port-587/3730353 CONNECTION id=flxyqzuqmjvip5rf src=hebei.2.60.in-addr.arpa[60.2.179.26]:56154
info SMTP/SMTP-Port-587/3730385 CONNECTION id=aumqjg63t473ataa src=78-73-158-59-no2664.tbcn.telia.com[78.73.158.59]:53726
info SMTP/SMTP-Port-25/3730462 CONNECTION id=pa63hcr42dwyg7ia src=[2.55.89.171]:38745
info SMTP/SMTP-Port-25/3730491 CONNECTION id=knvdof34rk2wsyyn src=[115.75.188.242]:50460
info SMTP/SMTP-Port-25/3730346 CONNECTION id=rlxn2jgnvw3j7vqq src=[94.141.120.77]:23805
info SMTP/SMTP-Port-25/3730378 CONNECTION id=bette3mkcse3bktk src=[94.141.120.77]:25794
info SMTP/SMTP-Port-25/3730388 CONNECTION id=znrfcp2w6jksinqa src=[94.141.120.77]:27156
info SMTP/SMTP-Port-25/3730411 CONNECTION id=nfqe65to44se753p src=[94.141.120.77]:27774
info SMTP/SMTP-Port-25/3730427 CONNECTION id=2g224vobq24ecciw src=[94.141.120.77]:27943
info SMTP/SMTP-Port-25/3730432 CONNECTION id=223djrcmdyocaza3 src=[94.141.120.77]:30499
info SMTP/SMTP-Port-25/3730443 CONNECTION id=36kdqicd5owmmdyv src=[94.141.120.77]:32345
info SMTP/SMTP-Port-25/3730462 CONNECTION id=xjagx44j7bd3x5rd src=[94.141.120.77]:33928
info SMTP/SMTP-Port-25/3730491 CONNECTION id=rchpir6gwu5s3fjo src=[94.141.120.77]:34881
info SMTP/SMTP-Port-25/3730494 CONNECTION id=ihrpjuwifiuntg73 src=[162.142.125.38]:41256
```
A huge list I have like that, interrupts my connections.

Thank you.

**Comment by louis-lau** [comment]
Fail2ban scans logs and bans based off of that. Can you explain why that doesn't work with zone-mta? I would have thought it would work fine.

**Comment by ravivgolov** [comment]
It doesn't work. How are you able to filter if all connections are the same?
Look at the example above. How can you determine which one is invalid? There's no 'failed' text or failed connection. I also think ZoneMTA doesn't automatically disconnect idle SMTP connections over time.

Haraka has connections failed to filter.

**Comment by louis-lau** [comment]
Ahh. I see what you mean. Looks to me like the default connection timeout is 10 minutes. You could lower it in the config of the interface.

https://github.com/zone-eu/zone-mta/blob/df06cba31adb78bb151679a292df0cd947246b4c/lib/smtp-interface.js#L145-L147

I'm not sure if the timeouts are logged though. Which is what you need.

I think you could also limit connections per ip if you put something like haproxy in front of zone-mta. Maybe that's a better fit? Though it adds some amount of complexity...

**Comment by ravivgolov** [comment]
Yes, the timeout is definitely what I need. There are no logs for this, which I can add, but the next ZoneMTA update will revert these changes. I need to think about what to do next... and HAProxy is too complicated.

I am not sure about limiting the connections, since valid connections are okay and I don't see a reason to restrict connections.

**Comment by louis-lau** [comment]
If you can add those logs and send a PR I don't see how they would be reverted in the next update.

**Comment by ravivgolov** [comment]
I think it is possible to add it like this:

```
   // Log socket timeouts
    this.server.on('connection', (socket) => {
        socket.on('timeout', () => {
            log.info(this.logName, 'SOCKET TIMEOUT src=%s:%s', socket.remoteAddress, socket.remotePort);
        });
    });
```
Insert it under:
`this.server = new SMTPServer(serverConfig);`
I haven't tested it yet.

I wish @andris9 could help us here, he would do it in a second. very helpful to auto ban bruteforce and DDoS.

**Comment by louis-lau** [comment]
I'd say try it and send a PR! :)

> bruteforce

Are failed authentication attempts also not logged? I can't really imagine that

**Comment by ravivgolov** [comment]
Failed authentication attempts are logged, but many of these involve making numerous connections before attempting authentication. I am seeing thousands of connections.

I will try to send a PR.

**Comment by ravivgolov** [comment]
BTW @louis-lau , do you know where the function that handles the transfer of messages to zonemta webadmin is located? I need to pass some additional custom parameters.

**Comment by ravivgolov** [comment]
Yes, I need the remotelog over UDP when sending data to ZMTA webadmin:
https://github.com/zone-eu/zmta-webadmin/blob/master/routes/udp.js

I need to get here more parameters I have added to the envelope during the smtp connection.

**Comment by ravivgolov** [comment]
I found a way but did it very nasty. I had to add in Zonemta core code...

**Comment by louis-lau** [comment]
A way to do what? Are you still talking about fail2ban or are you talking about zonemta-webadmin logging?

**Comment by ravivgolov** [comment]
The logging, the fail2ban - no success

**Comment by louis-lau** [comment]
Seeing as you are customizing core workings it's not surprising you'd need to modify core code. It's not dirty if you manage the patches/fork properly. Or if you contribute your changes back upstream.

**Comment by ravivgolov** [comment]
I think the code does not have timeout destroy - or I am wrong? smtp-interface.js

**Comment by louis-lau** [comment]
From the socketTimeout variable I linked, you can see it being given to the smtp-server library. Here's some code relevant to socket timeouts:
https://github.com/nodemailer/smtp-server/blob/18ad40ffe5704705e73099004c8d2e6580f4497d/lib/smtp-connection.js#L318

If that's what you meant by timeout destroy? Otherwise, I'm not sure what you meant. I just searched for a little bit, I have no significant experience with developing in either of these projects.

**Comment by ravivgolov** [comment]
Yes, but I'm not sure if I can directly edit the smtp-server library linked to zonemta. If the library is updated, the code will be lost.
I either do not know how to develop this properly in zonemta....

But yeah, good hint. thank you.

**Comment by louis-lau** [comment]
I mean, that library is also open source. If you want to keep it just for yourself you'll need to fork it. Otherwise just contribute your changes and they'll be there the next update. But I do think I said that before :)

**Comment by ravivgolov** [comment]
Yeah, I understand. I need to orgenize here everything.

I tried that file and updated this part:

```
_onTimeout() {
        
        const timestamp = new Date().toISOString(); // ISO 8601 format timestamp
        const logMessage = `[${timestamp}] Connection timeout fired ip=${this.remoteAddress}\n`;
    
        // Log to console
        console.log(logMessage);
    
        // Append to file
        fs.appendFile(path, logMessage, (err) => {
            if (err) {
                console.error(`Failed to write to log file: ${err.message}`);
            }
        });
        
        this.send(421, 'Timeout - closing connection');
    }
```

That is not firing at all. I'm not sure if this is the correct file.

**Comment by ravivgolov** [comment]
I think this is not the right place, nothing fired... I have lowered the socket to 20 seconds to check.

**Comment by ravivgolov** [comment]
Okay, This is the right place, I have no idea why now it is working. I did nothing. funny ...

**Comment by ravivgolov** [comment]
So yeah, I found now, not all are timeout:
info SMTP/SMTP-Port-587/2344663 CONNECTION id=ie3vfyixncjvvj34 src=m121-202-154-25.smartone.com[121.202.154.25]:40408

This can establish and close a connection, but we are unable to observe the client closing the connection. I tested this using telnet and closed the connection, but nothing was logged in zonemta to indicate this.
