### ISSUE TITLE
Sending zone hostname parameter must be configurable

### ISSUE THREAD

**Issue by manalejandro** [zone-eu/zone-mta#428]
https://github.com/zone-eu/zone-mta/blob/master/lib/sending-zone.js#L7

**Comment by louis-lau** [comment]
It is.

https://github.com/zone-eu/zone-mta/blob/cfed6c89812953c742fdf7b4ab1f33c745db198e/config/default.js#L371

**Comment by manalejandro** [comment]
My apologies, it is true that it is configurable, i have misused the address parameter as array from the beginning, thanks.
