### ISSUE TITLE
Zone-Mta unable to send Bounces correctly to Mailtrain 

### ISSUE THREAD

**Issue by wallydz** [zone-eu/zone-mta#53]
info Sender/default/30766 158e0fdcc80000ab4b.001 REJECTED[rate] from=xxxx@xxxxx[xxx@xxxxx.xx] to=xxxx@xxxx.xxxxx mx=mx1.hotmail.com (421 RP-001 (SNT004-MC1F11) Unfortunately, some messages from xxxxxxxxx weren't sent. Please try again. We have limits for how many messages can be sent per hour and per day. You can also refer to http://mail.live.com/mail/troubleshooting.aspx#errors.)
/opt/zone-mta/lib/sender.js:716
        if (/^mailer\-daemon@/i.test(delivery.parsedEnvelope.from)) {
                                                            ^

TypeError: Cannot read property 'from' of undefined
    at Sender.sendBounceMessage (/opt/zone-mta/lib/sender.js:716:61)
    at Immediate.setImmediate (/opt/zone-mta/lib/sender.js:301:45)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
ERR! Child/default/30766 Sender process a165af73786ed652063a for default exited with 1

**Comment by andris9** [comment]
I think this has been already fixed some time ago. Try to upgrade zone-mta to latest master. The config format has changed a bit, so compare your exsiting production.json against the one generated by Mailtrain [setup script](https://github.com/andris9/mailtrain/blob/master/setup/install.sh#L127-L197)
