### ISSUE TITLE
setgid/setuid fail does not affect execution

### ISSUE THREAD

**Issue by jkramarz** [zone-eu/zone-mta#6]
If user starting the server has no privileges to set uid or gid to defined in configuration, it is reported on "info" log level (isn't it a bit more important fact?) and does not halt starting the application.
It may result in running service from `root` user, if starting from Sysvinit with wrong configuration.

**Comment by andris9** [comment]
Fixed with 5aee0cb0fd270f60f6e8dacf350224c7216bb72e
