### ISSUE TITLE
Enhancement: same IP pair (IPV4/IPV6) for the same sender and recipient.

### ISSUE THREAD

**Issue by Dexus** [zone-eu/zone-mta#68]
Is it possible to add a module to set the same IP pair for the sender and recipient?

With a option to set the IPV6 as first option to try to send over it if the host has a IPV6. And/Or a option to disable IPV6 completely.

**Comment by andris9** [comment]
Do you mean like using IPv6 settings per specific sender or recipient? Because for a sending zone you can use the [preferIPv6 and ignoreIPv6](https://github.com/zone-eu/zone-mta/blob/master/config/default.js#L322-L327) options?

**Comment by Dexus** [comment]
I mean something like: https://github.com/haraka/Haraka/wiki/Outbound-Improvements#supporting-the-same-outgoing-ip-stack-ipv4-and-ipv6-for-common-sender-and-recipient

**Comment by andris9** [comment]
You can now add domain specific DNS options like show [here](https://github.com/zone-eu/zone-mta/blob/master/config/default.js#L423-L426) that override the defaults for this specific domain
