### ISSUE TITLE
Zonemta with Forever

### ISSUE THREAD

**Issue by w3update** [zone-eu/zone-mta#73]
Hi,

Any idea to run zonemta permanent with forever command?
or is there any other way to keep it running once terminal closed?
thanks

**Comment by w3update** [comment]
OK I managed to start with forever by issuing
forever start -c "npm start" ./
is there any other way around also?

**Comment by andris9** [comment]
I use systemd service file (`zone-mta-app.service`) to keep the app up and running:

```
Description=ZoneMTA SMTP server

[Service]
Environment="NODE_ENV=production"
WorkingDirectory=/opt/zone-mta-app
ExecStart=/usr/bin/node ./node_modules/zone-mta/bin/zone-mta.js run -d . -c config.json
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by w3update** [comment]
thankyou very much i got it.
what would be service content in the case of zone-mta-admin if it happens to create a service file named zone-mta-admin.service
-------------------------------------------------------------------------
[Unit]
Description=Zone-MTA Admin
[Service]
Environment="NODE_ENV=production"
WorkingDirectory=/opt/zone-mta/node_modules/zmta-webadmin
ExecStart=/usr/bin/node -max-old-space-size=2048 app.js
Type=simple
Restart=always

[Install]
WantedBy=multi-user.target
-------------------------------------------------------------------------
will above work ?

**Comment by w3update** [comment]
[Unit]
Description=Zone-MTA Admin
[Service]
WorkingDirectory=/opt/zone-mta/node_modules/zmta-webadmin
#Environment="NODE_ENV=production"
ExecStart=/usr/bin/node server.js
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target

I got it working with above service code.

thanks
