### ISSUE TITLE
Zonemta configuration changes in effect

### ISSUE THREAD

**Issue by w3update** [zone-eu/zone-mta#74]
Hi,

I made changes in default.js and then I stop and start npm.
but the same does not reflect.
Do i need to compile the app with certain command? and start. I guess I missing some step.
thanks

**Comment by w3update** [comment]
I guess changes needs to made in config.json
---- "See default.js for all possible config options that you can use for config.json in your app folder."
thanks

**Comment by andris9** [comment]
if you start the app from command line with `zone-mta` command then you should provide the config file as a configuration option. I think there's some issues currently with paths, so you should run this command from your app directory. The configuration in your config file (eg. config.json) is merged with default.js where config.json changes override values from default.js

```
$ zone-mta create path/to/app # creates a new application template
$ cd /path/to/app # navigate to the app folder
$ zone-mta run -d . -c config.json # run the app from the app dir
```
