### ISSUE TITLE
Can this integrated with list management like interspire , mailwizz ?

### ISSUE THREAD

**Issue by amitsquare** [zone-eu/zone-mta#77]
Just started exploring zone-mta .
Can this be integrated with email list management tool like interspire , mailwizz ?

thanks

**Comment by andris9** [comment]
You can use it instead of Postfix or Exim or any other SMTP smarthost that is used to send outbound emails. If your email list software sends messages to a SMTP server for further delivery then ZoneMTA can be that server.
