### ISSUE TITLE
All pool addresses are blacklisted, but Zone-MTA keeps sending messages

### ISSUE THREAD

**Issue by virtuaCode** [zone-eu/zone-mta#80]
Hello,

is it normal that Zone-MTA keeps sending messages with an address-pool, that have all its IP-addresses blacklisted for a specific domain? If yes, does that mean i've to add these blacklisted domains manually to the suppression list to stop the transfer to them completely?

Thanks for help!

**Comment by andris9** [comment]
If all messages are blacklisted then ZoneMTA should make a single attempt to send using a random IP from the pool (even though it is blacklisted) and if that fails then bounces immediatelly.
