### ISSUE TITLE
Posting json to API (/send) is broken

### ISSUE THREAD

**Issue by rquast** [zone-eu/zone-mta#81]
Firstly.. cool project! Thanks!

I tried doing a post to /send of the json, but there's an instantiation bug for MailComposer. Tried doing it with the raw method and that worked fine.

```
{"code":"InternalError","message":"Class constructor MailComposer cannot be invoked without 'new'"}
```

Any chance for a quick patch? Looks like it needs to do a new, call compile() and return the envelope.

**Comment by andris9** [comment]
Thanks. This is now fixed.
