### ISSUE TITLE
DKIM keys missing from delivery?

### ISSUE THREAD

**Issue by rquast** [zone-eu/zone-mta#82]
I have configured dkim (loads up, and have tested /get-config with a POST - all ok).

https://github.com/zone-eu/zone-mta/blob/f80970c7cdac109ecf030661c796157382005126/lib/sender.js#L941

```
console.log(delivery.dkim) ....
{ hashAlgo: 'sha256',
  debug: null,
  bodyHash: '8v/UdiUSlasCEmy3pq2egp6iEbNqzWb5mTQUQgBfRy4=' }
```

At this point, it can calculate the hash, but there is no delivery.dkim.keys - so it won't add the header.

Did I do something wrong in the configuration? It's all enabled as far as I can tell.

**Comment by andris9** [comment]
The DKIM handling is a bit shaky and going through some structural changes. In the meantime you could try to use this [example plugin](https://gist.github.com/andris9/ef6e0f9014b6502077cf2d938412f400) for enabling DKIM support.

**Comment by rquast** [comment]
Thanks!

**Comment by rquast** [comment]
Works well. :+1:

Notes: 

I had to edit out the config dkim enabled check in sender.js for sendMessage to work. Also removed all of the new dkim code in api-server.js

I also had to use /send rather than /send-raw .. raw didn't calculate the body hash correctly (with the curl tests), but it worked with /send. I'm guessing something to do with CR/LF.
