### ISSUE TITLE
DKIM - Incorrect body hash (random)

### ISSUE THREAD

**Issue by rquast** [zone-eu/zone-mta#83]
I haven't been able to single out the cause yet, but when I use *both* text and html, the body hash is incorrect. I've attached two emails from my system that show the dkim pass/failure notice in the header. Has the hashing been tested for multipart messages?

[emails.zip](https://github.com/zone-eu/zone-mta/files/1090260/emails.zip)

**Comment by rquast** [comment]
To confirm, works fine for html only or text only, but not multipart.

**Comment by rquast** [comment]
Small hunch.. it may be that my emails are encoded in quoted-printable rather than 7bit.
Content-Transfer-Encoding: quoted-printable

I'm passing the json straight to /send with "to", "html", "text" and so on. The transfer encoding type I am sending the json with is UTF-8.

**Comment by rquast** [comment]
I've just tried another email template, this one with less HTML, and there is no body hash error. Attached the email for comparison.
[multipart_dkim_success.eml.zip](https://github.com/zone-eu/zone-mta/files/1090486/multipart_dkim_success.eml.zip)

**Comment by andris9** [comment]
Thanks. I'll be offline for the next days, so I'll take a look on this a bit later

**Comment by andris9** [comment]
Sorry for the delay. I just looked at the failed message and I can't replicate it. if I try to re-send the same message then the DKIM body signature is calculated correctly. Which version of Zone-MTA are you using btw?

**Comment by rquast** [comment]
Sorry, I should have got back to you on this but I got really busy. I've continued this discussion here: https://github.com/zone-eu/zone-mta/issues/99
