### ISSUE TITLE
how to configure to connect zonemta from external softwares?

### ISSUE THREAD

**Issue by ajmalkhanjamro** [zone-eu/zone-mta#84]
hello i wanna setup zonemta to connect from external ips with authentication like another smtp how can i do that please guide and iam very new to zonemta setup

**Comment by rquast** [comment]
make it listen on 0.0.0.0 instead of 127.0.0.1 for the smtp config

**Comment by andris9** [comment]
If you want to use authentication then you need something to authenticate against. Here's an [example plugin](https://gist.github.com/andris9/938a73247b1e76ec515293f580dfa802) for static authentication. See from the [plugins documentation](https://github.com/zone-eu/zone-mta/tree/master/plugins) for help about creating and using plugins.
