### ISSUE TITLE
Any advice on bulk email plugin? [question]

### ISSUE THREAD

**Issue by vodolaz095** [zone-eu/zone-mta#86]
Hello!
For example, i have RethinkDB/Mongo/*SQL with list of addresses i want to deliver messages to.
How can i write plugin for your module, that 
1. waits for command to start sending messages to batch.
2. queries database, gets list of emails from it, and queues them for delivery using your zoneMTA.

I mean, how it is possible to write one more way to queue emails for your system, not POST hooks and not SMTP servers?

Can you provide any advices for it?

Thanks in advance

**Comment by andris9** [comment]
ZoneMTA plugins are used to manipulate messages that are passing though. ZoneMTA itselt is not the source of messages. You should generate these messages somewhere else and pass these to ZoneMTA as to a regular smarthost for delivery.

What you are thinking of contains some kind of scheduler that checks for new emails from somewhere. ZoneMTA does not have any scheduler functionality, everything happens in a trigger based way: client connects to SMTP and pushes new message for delivery. This action triggers all plugins that manipulate on that message.

**Comment by vodolaz095** [comment]
Great thanks for prompt answer!

**Comment by andris9** [comment]
😃  next time I'll try to be even faster, maybe I can answer in 26, not in 27 days
