### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by doc-tongue** [zone-eu/zone-mta#88]
Building Wildduck yesterday, the docker image had a missing OS dependancy on build from the optional npm dependancies.  As a result the docker port binding from host to container or proxy to container would not work.  I am experiencing the  same issue here however see no errors with the missing dependancy.  Currently only testing the api port using the default 8080.

`FROM node:8.2.1-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash curl

WORKDIR /usr/src/app

RUN mkdir config

COPY package.json ./
RUN npm install -g  --no-optional zone-mta
RUN zone-mta create /usr/src/app

CMD ["zone-mta", "run","-d","./data","-c","config.json"]`

`version: '3.3'
services:
  wildduck:
    image: houlagins/wildduck:test
    ports:
      - "993:993"
      - "995:995"
    networks:
      - frontend
      - backend
    environment:
      CONFIG: /wildduck.toml
    configs:
      - wildduck.toml
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=frontend"
        - "traefik.backend=wildduck"
        - "traefik.frontend.rule=Host:wildduck.localhost"
      resources:
        limits:
          memory: 500M
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
        update_config:
          parallelism: 1
          delay: 5s

  zonemta:
    image: houlagins/zonemta:test
    ports:
      - "2525:2525"
      - "8081:8081"
    networks:
      - frontend
      - backend
    configs:
      - source: zonemta.json
        target: /usr/src/app/data/config.json
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=frontend"
        - "traefik.backend=zonemta"
        - "traefik.frontend.rule=Host:zonemta.localhost"
      resources:
        limits:
          memory: 500M
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
        update_config:
          parallelism: 1
          delay: 5s
configs:
  wildduck.toml:
    external: true
  zonemta.json:
    external: true

networks:
  backend:
    external: true
  frontend:
    external: true`

Wildduck dockerfile:
`FROM node:8.2.1-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash curl

WORKDIR /usr/src/app

RUN mkdir config

COPY package.json ./

RUN npm install -q --no-optional --production

COPY . ./

CMD ["sh", "entrypoint.sh"]`
//entry point looks for config or not then runs

Curl localhost:2525 and Curl localhost:8080 work from with container however the binding to host or proxy via the docker networking seems to be failing.  Again the same problem yesterday was resulting from missing OS dependancies make, g++ ect.  I cannot seem to find the missing deps here.  
Thank You,

**Comment by doc-tongue** [comment]
When npm install locally I still see modern-syslog not withstanding  --no-optional flag.  I have tried adding to the image with still no luck:

`RUN apk update && apk upgrade && \
    apk add --no-cache bash curl build-base python gcc g++ clang`

**Comment by andris9** [comment]
Do you have a package-lock.json file somewhere? --no-optional should normally disable the syslog dependency

**Comment by doc-tongue** [comment]
Yes thanks.  Removed the lock.

**Comment by doc-tongue** [comment]
Still no luck with the image though :-(.  Still won't bind with dockers ports.  Can you see a possible OS dep I am missing?

**Comment by andris9** [comment]
I don't know if there's a difference but the ports are bound to 127.0.0.1 by default. maybe you should change these to 0.0.0.0?
