### ISSUE TITLE
Suggestion : Load-Balancing 

### ISSUE THREAD

**Issue by wallydz** [zone-eu/zone-mta#9]
Maybe adding a multi zone-mta connected as master/slaves
Would be useful in case you want use Multiple MX to send a large number of emails

**Comment by andris9** [comment]
Could you explain a little bit more how you would see the master/slave feature to work?

**Comment by wallydz** [comment]
For now we are using Haproxy / Postfix  ( http://blog.haproxy.com/2012/06/30/efficient-smtp-relay-infrastructure-with-postfix-and-load-balancers/ )
But As ZONE-MTA have API and AUTH why not something the same ?  i understand that Zone-MTA work with Zones but when we are using one server and mutliple IP 
It would be nice to use Zone-MTA on multiple VPS Different IP adresss but all communicate in the end to Mailtrain

**Comment by andris9** [comment]
Sorry for the delayed response. I see what you mean now. I think that adding the option to automatically share load between multiple ZoneMTA instances (connect to master that would pass the job on to some worker instance) would not be more effective than using HAProxy (or even Nginx) in front and letting HAProxy to balance the load.

Adding similar load sharing features to ZoneMTA would basically mean re-implementig the same functionality current load balancer already have and this would be too much in the current stage.

It would make more sense if we would replace LevelDB with something external, eg. Cassandra as in that case you could have several instances connected to the same DB back end but the current LevelDB is one machine centric and doing anything more distributed would be quite difficult.

So for now the right way to go would be to use a load balancer (HAProxy, Nginx) in front of several separate and not-connected ZoneMTA instances
