### ISSUE TITLE
Limit max messages per connection

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#90]
Yahoo wants max 20 messages per connection. Can this be set in config or a plugin is required ?

**Comment by andris9** [comment]
Currently ZoneMTA sends just a single message per connection. Re-using connections is planned but for now there's just 1 message.

**Comment by dazoot** [comment]
So after 1 message the connection is closed ?

**Comment by andris9** [comment]
Yes. Whenever a message is about to be sent, an outbound IP address is selected, that address is used to connect to the destination MX, the message is delivered and connection is closed. This is needed to be able to rotate IP's for different messages and also to re-send deferred messages using the same IP as previously.
