### ISSUE TITLE
Multiple dkim headers

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#91]
Multiple dkim headers nowadays id a must. See Google Feedback-Id. Plugin required ?

**Comment by andris9** [comment]
You can add as many signatures as you wish but you need a custom plugin for it. See the default [dkim plugin](https://github.com/zone-eu/zone-mta/blob/master/plugins/core/dkim.js#L24-L36) how it pushes multiple DKIM keys to the signature array. For every entry in the` delivery.dkim.keys` array a separate DKIM signature is added

**Comment by andris9** [comment]
Btw Feedback-Id is not signed by default. You could use the extra headerFieldNames property when setting up dkim data, its a string that should include all headers you want to sign separated by colon:

        delivery.dkim.keys.push({
            domainName: 'example.com',
            keySelector: 'selector',
            privateKey: '---- BEGIN PRIVATE KEY...',
            headerFieldNames: 'subject:message-id:feedback-id:...'
        });
