### ISSUE TITLE
Tweak retry policy

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#92]
What is the retry policy for a message if it gets deferred ? Can it be tweaked ?

**Comment by andris9** [comment]
The values are hardcoded [here](https://github.com/zone-eu/zone-mta/blob/4ad34ea8a5bd811b55de35619cb811d424d37c77/lib/sender.js#L21-L39)

**Comment by andris9** [comment]
Every time a message gets deferred, its defer counter gets incremented by 1 and the resulting array item from ttlItems is used to define the next delivery attempt. Once there are no more entries in the array to try, the message gets rejected.

**Comment by dazoot** [comment]
Does the retry happens with same ip ? 

The next delivery attempt is calculated from the behinning or since the last retry ?

**Comment by andris9** [comment]
The IP to use is calculated by a hash function so as long as you do not change the pool structure (not not add or remove IPs or change the ratio of any IP), then the IP remains the same for the same message. The IP to use calculated [here](https://github.com/zone-eu/zone-mta/blob/master/lib/sending-zone.js#L197-L200)

Retry ttl is always from current time. So if the retry counter is zero (the first retry), the ttl is 5 minutes from now, next retry counter is 7 minutes (so the total from begininnig is 12 minutes), next is 8 minutes (so the total is 20 minutes) and so on.
