### ISSUE TITLE
TypeError: delivery.dkim.keys.push is not a function

### ISSUE THREAD

**Issue by bbbart** [zone-eu/zone-mta#93]
Hi!

This might be related to #91 perhaps.

I just configured Mailtrain to use ZoneMTA hosted on the same server. Works fine. But as soon as I enabled DKIM (API key, DKIM key, etc...), my mails got stuck in the default queue of ZoneMTA.

The logs tell me: `TypeError: delivery.dkim.keys.push is not a function` at `.../plugins/core/dkim.js:24`.

And indeed, `delivery.dkim.keys` doesn't hold an Array at that point, but an object. By the way, a simple `console.log` debug statement tells me that that object at that point already holds my domain, selector and private key, so I'm not sure why the code seems to want to push them in there again?

**Comment by bbbart** [comment]
Commenting out [this block](https://github.com/zone-eu/zone-mta/blob/master/plugins/core/dkim.js#L24-L36) makes it work for now, but I'm pretty sure that's not the correct way to move forward. :-)

With 'work' I mean that mails are being sent out *and* are correctly DKIM signed.

**Comment by witzig** [comment]
In [your case](https://github.com/Mailtrain-org/mailtrain/issues/316), where ZoneMTA uses the `core/http-config` plugin to fetch the DKIM settings from Mailtrain, there's no need to enable/configure the `core/dkim` plugin.

Yet you revealed a bug which does seem to root in Mailtrain. It seems Mailtrain should return an Array [here](https://github.com/Mailtrain-org/mailtrain/blob/master/routes/webhooks.js#L322-L326). Since you're already debugging, could you give that a try? :-)

**Comment by bbbart** [comment]
Ah, that seems to work. Here's what I did:

1. I again uncommented lines 24 to 36 in `node_modules/zone-mta/plugins/core/dkim.js` from ZoneMTA
1. I changed lines 320 to 328 in `routes/webhooks.js` from Mailtrain to
```
res.json({
        dkim: {
                keys: [{
                    domainName: configItems.dkimDomain || domain,
                    keySelector: configItems.dkimSelector,
                    privateKey: configItems.dkimPrivateKey
                },]
        }
});
```
3. I sent a small test campaign from Mailtrain and it was well received, DKIM signed and all

Would you still recommend disabling the dkim plugin for ZoneMTA at this point?

**Comment by witzig** [comment]
Thank you. The fix in Mailtrain looks fully backwards compatible with earlier versions of ZoneMTA and the current config has been working fine so far thanks to [this](https://github.com/zone-eu/zone-mta/blob/cfccfea4e8f5175ca948a89543ca96ff338fe71d/lib/sender.js#L947). Will be fixed tomorrow.

> Would you still recommend disabling the dkim plugin for ZoneMTA at this point?

Use either the dkim or the http-config plugin. If performance matters, use the dkim plugin.
