### ISSUE TITLE
option to disable same ip retry

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#94]
Would be good to have an option to disable same ip retry for a message.

**Comment by dazoot** [comment]
Changing line 199 in lib/sending-zone.js:
```
let index = Math.abs(crc32.str(key) % pool.length);
```
to Random would do ?

**Comment by deepvoice** [comment]
along the same lines it would be nice to have a header option that would force a particular IP in the pool

**Comment by andris9** [comment]
Same IP retry is used to handle greylisting. For custom IP handling you can use plugins.

For example to always use the same local IP create the following file:  plugins/custom-ip.js

```javascript
module.exports.title = 'Custom IP';
module.exports.init = function(app, done) {
    app.addHook('sender:fetch', (delivery, next) => {
        // set whatever IP you want to use here
        delivery.zoneAddress = {
            address: '1.2.3.4',
            name: '1.2.3.4.hostname'
        };
        next();
    });
    done();
};
```

and then enable this plugin with config/plugins/custom-ip.toml (assuming the same configuration structure as in [zone-mta-template](https://github.com/zone-eu/zone-mta-template)):

```toml
[custom-ip]
enabled=["sender"]
```
