### ISSUE TITLE
ZoneMTA coexistence with (or replacement for) Postfix

### ISSUE THREAD

**Issue by deisner** [zone-eu/zone-mta#95]
I have ZoneMTA installed on an Ubuntu server running Mailtrain. I'd like to receive incoming SMTP mail. For example, I'd like email sent to admin@mymailtrainserver.foo.org to go to my work email address. Normally I'd set this up in /etc/aliases. I'd also like cron to be able to send mail to my work email (via MAILTO=).

The ZoneMTA service configuration explicitly conflicts with postfix (and sendmail and exim):
`Conflicts=sendmail.service exim.service postfix.service`

Can ZoneMTA be configured to meet the requirements in the first paragraph? If not, what's the Right Way to achieve them? Thanks!

**Comment by andris9** [comment]
The only conflict is in port usage. If Postfix listens on 25 and ZoneMTA on 587, then there's no issues and you can remove the conflicts clause from the service file.
