### ISSUE TITLE
SMTP accounting and authentication

### ISSUE THREAD

**Issue by masihfathi** [zone-eu/zone-mta#96]
I am very new to zonemta, had a basic question, Is it possible to create a  Transactional Email service (api and SMTP) like mailgun.com, sendgrid.com with zonemta
And, if possible, What needs to know? I think I can make the API  with PHP and handle API, But I do not have any idea to build SMTP accounting and authentication, For example, build and monitor an SMTP account (bounce, deliver ...)
Thanks!

**Comment by andris9** [comment]
You are probably looking for something like [Postal](https://github.com/atech/postal), I think that ZoneMTA is too low level for your needs.

**Comment by masihfathi** [comment]
tnx
