### ISSUE TITLE
Is it possible to make a plugin for get a notification of success on sent?

### ISSUE THREAD

**Issue by TheJoin95** [zone-eu/zone-mta#97]
Hi!
I'd like to create a plugin to know if a message queued was delivered without errors (like Amazon SNS for Amazon SES).
I can replicate almost everything from the http-bounce plugin (I mean for sending a notification via http), but i don't know if exists a hook that manage the message after the send. It exists?

There is any other way to make this? Eg: make an api call for searching the message by a custom header?
Thanks

**Comment by andris9** [comment]
Yes, you can use the 'log:entry' hook like this (should be enabled for 'main'):

```javascript
app.addHook('log:entry', (entry, next) => {
    switch(entry.action){
        case 'ACCEPTED': console.log('Message sent', entry); break;
        case 'REJECTED': console.log('Message hard bounced', entry); break;
        case 'DEFERRED': console.log('Message soft bounced', entry); break;
    }
});
```
